// Package contract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package contract

import (
	"time"
)

const (
	RoleScopes roleContextKey = "role.Scopes"
)

// Defines values for AttentionReason.
const (
	AttentionReasonAiFailed        AttentionReason = "ai_failed"
	AttentionReasonTooFewPassed    AttentionReason = "too_few_passed"
	AttentionReasonTooFewQualified AttentionReason = "too_few_qualified"
)

// Valid indicates whether the value is a known member of the AttentionReason enum.
func (e AttentionReason) Valid() bool {
	switch e {
	case AttentionReasonAiFailed:
		return true
	case AttentionReasonTooFewPassed:
		return true
	case AttentionReasonTooFewQualified:
		return true
	default:
		return false
	}
}

// Defines values for Availability.
const (
	AvailabilityImmediate   Availability = "immediate"
	AvailabilityOneMonth    Availability = "one_month"
	AvailabilityTwoWeeks    Availability = "two_weeks"
	AvailabilityUnavailable Availability = "unavailable"
	AvailabilityUnknown     Availability = "unknown"
)

// Valid indicates whether the value is a known member of the Availability enum.
func (e Availability) Valid() bool {
	switch e {
	case AvailabilityImmediate:
		return true
	case AvailabilityOneMonth:
		return true
	case AvailabilityTwoWeeks:
		return true
	case AvailabilityUnavailable:
		return true
	case AvailabilityUnknown:
		return true
	default:
		return false
	}
}

// Defines values for CandidateStatus.
const (
	CandidateStatusActive   CandidateStatus = "active"
	CandidateStatusArchived CandidateStatus = "archived"
)

// Valid indicates whether the value is a known member of the CandidateStatus enum.
func (e CandidateStatus) Valid() bool {
	switch e {
	case CandidateStatusActive:
		return true
	case CandidateStatusArchived:
		return true
	default:
		return false
	}
}

// Defines values for FilterName.
const (
	FilterNameAvailability    FilterName = "availability"
	FilterNameCertifications  FilterName = "certifications"
	FilterNameExperience      FilterName = "experience"
	FilterNameProfile         FilterName = "profile"
	FilterNameSoftware        FilterName = "software"
	FilterNameTimezoneOverlap FilterName = "timezone_overlap"
)

// Valid indicates whether the value is a known member of the FilterName enum.
func (e FilterName) Valid() bool {
	switch e {
	case FilterNameAvailability:
		return true
	case FilterNameCertifications:
		return true
	case FilterNameExperience:
		return true
	case FilterNameProfile:
		return true
	case FilterNameSoftware:
		return true
	case FilterNameTimezoneOverlap:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusDegraded HealthStatus = "degraded"
	HealthStatusOk       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusDegraded:
		return true
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for JobStatus.
const (
	JobStatusFailed    JobStatus = "failed"
	JobStatusQueued    JobStatus = "queued"
	JobStatusRunning   JobStatus = "running"
	JobStatusSucceeded JobStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case JobStatusFailed:
		return true
	case JobStatusQueued:
		return true
	case JobStatusRunning:
		return true
	case JobStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for MatchStatus.
const (
	MatchStatusApproved      MatchStatus = "approved"
	MatchStatusPendingReview MatchStatus = "pending_review"
	MatchStatusProposed      MatchStatus = "proposed"
	MatchStatusRejected      MatchStatus = "rejected"
	MatchStatusSwapped       MatchStatus = "swapped"
)

// Valid indicates whether the value is a known member of the MatchStatus enum.
func (e MatchStatus) Valid() bool {
	switch e {
	case MatchStatusApproved:
		return true
	case MatchStatusPendingReview:
		return true
	case MatchStatusProposed:
		return true
	case MatchStatusRejected:
		return true
	case MatchStatusSwapped:
		return true
	default:
		return false
	}
}

// Defines values for Persona.
const (
	PersonaEmployer Persona = "employer"
	PersonaOps      Persona = "ops"
	PersonaTalent   Persona = "talent"
)

// Valid indicates whether the value is a known member of the Persona enum.
func (e Persona) Valid() bool {
	switch e {
	case PersonaEmployer:
		return true
	case PersonaOps:
		return true
	case PersonaTalent:
		return true
	default:
		return false
	}
}

// Defines values for ReviewAction.
const (
	ReviewActionApprove   ReviewAction = "approve"
	ReviewActionReject    ReviewAction = "reject"
	ReviewActionRelease   ReviewAction = "release"
	ReviewActionSwap      ReviewAction = "swap"
	ReviewActionUnrelease ReviewAction = "unrelease"
)

// Valid indicates whether the value is a known member of the ReviewAction enum.
func (e ReviewAction) Valid() bool {
	switch e {
	case ReviewActionApprove:
		return true
	case ReviewActionReject:
		return true
	case ReviewActionRelease:
		return true
	case ReviewActionSwap:
		return true
	case ReviewActionUnrelease:
		return true
	default:
		return false
	}
}

// Defines values for RoleMatchState.
const (
	RoleMatchStateInReview       RoleMatchState = "in_review"
	RoleMatchStateNeedsAttention RoleMatchState = "needs_attention"
	RoleMatchStateReady          RoleMatchState = "ready"
)

// Valid indicates whether the value is a known member of the RoleMatchState enum.
func (e RoleMatchState) Valid() bool {
	switch e {
	case RoleMatchStateInReview:
		return true
	case RoleMatchStateNeedsAttention:
		return true
	case RoleMatchStateReady:
		return true
	default:
		return false
	}
}

// Defines values for RoleStatus.
const (
	RoleStatusClosed RoleStatus = "closed"
	RoleStatusFilled RoleStatus = "filled"
	RoleStatusOpen   RoleStatus = "open"
)

// Valid indicates whether the value is a known member of the RoleStatus enum.
func (e RoleStatus) Valid() bool {
	switch e {
	case RoleStatusClosed:
		return true
	case RoleStatusFilled:
		return true
	case RoleStatusOpen:
		return true
	default:
		return false
	}
}

// Defines values for RunStatus.
const (
	RunStatusMatched        RunStatus = "matched"
	RunStatusNeedsAttention RunStatus = "needs_attention"
)

// Valid indicates whether the value is a known member of the RunStatus enum.
func (e RunStatus) Valid() bool {
	switch e {
	case RunStatusMatched:
		return true
	case RunStatusNeedsAttention:
		return true
	default:
		return false
	}
}

// AttentionReason Why a matching run needs attention. `too_few_passed`: zero or one candidate passed the hard filters. `too_few_qualified`: fewer than two of the reranked scored at or above the minimum. `ai_failed`: the AI service failed or timed out during the rerank, and no matches were written. When more than one applies, `ai_failed` is reported first, then `too_few_passed`.
type AttentionReason string

// Availability What the resume suggests. The filters use `WorkAvailability`, which the candidate supplies.
type Availability string

// AvailabilityCheck One candidate against one role's availability and time-zone filters.
type AvailabilityCheck struct {
	// CandidateID A UUID, as text.
	CandidateID   ID     `json:"candidate_id"`
	CandidateName string `json:"candidate_name"`

	// OverlapHours Hours of the role's working day the candidate's working hours cover; null when the role has no time zone or the candidate no availability.
	OverlapHours *float64 `json:"overlap_hours"`
	Passed       bool     `json:"passed"`

	// Reasons Why the candidate does not pass, in words; empty when they do.
	Reasons []string `json:"reasons"`
}

// CalendarDate A calendar day, `YYYY-MM-DD`.
type CalendarDate = Date

// Candidate defines model for Candidate.
type Candidate struct {
	CreatedAt time.Time `json:"created_at"`
	Email     *string   `json:"email"`
	FullName  string    `json:"full_name"`

	// ID A UUID, as text.
	ID         ID      `json:"id"`
	Location   *string `json:"location"`
	Phone      *string `json:"phone"`
	ResumeText string  `json:"resume_text"`

	// Source Where the record came from; `self` when talent created it.
	Source    *string         `json:"source"`
	Status    CandidateStatus `json:"status"`
	UpdatedAt time.Time       `json:"updated_at"`
}

// CandidateInput Body for creating or updating a candidate. Every field is optional on
// the wire so a `PUT` can send only what changes; `full_name` is required
// when creating and may not be nulled. `null` clears an optional field.
type CandidateInput struct {
	Email    *string `json:"email,omitempty"`
	FullName *string `json:"full_name,omitempty"`
	Location *string `json:"location,omitempty"`
	Phone    *string `json:"phone,omitempty"`

	// ResumeText `null` clears it to an empty string.
	ResumeText *string `json:"resume_text,omitempty"`
	Source     *string `json:"source,omitempty"`

	// Status Defaults to `active` on create.
	Status *CandidateStatus `json:"status,omitempty"`
}

// CandidateStatus defines model for CandidateStatus.
type CandidateStatus string

// ClockTime A time of day on a 24-hour clock, `HH:MM`.
type ClockTime = string

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`

	// Fields Per-field messages on a 422.
	Fields *map[string]string `json:"fields,omitempty"`
}

// FilterName A hard filter, in the order they are applied.
type FilterName string

// FilterRun One run of a role's hard filters over the active candidates, and the shortlist retrieved from those who passed.
type FilterRun struct {
	// AttentionDetail The AI service's error when `attention_reason` is `ai_failed`; otherwise `null`.
	AttentionDetail *string `json:"attention_detail"`

	// AttentionReason Why the run needs attention; `null` unless `match_status` is `needs_attention`.
	AttentionReason *AttentionReason `json:"attention_reason"`

	// CandidateIds Who passed every filter, by name. A record of the run; a candidate deleted since stays listed.
	CandidateIds []ID      `json:"candidate_ids"`
	CreatedAt    time.Time `json:"created_at"`

	// ID A UUID, as text.
	ID ID `json:"id"`

	// MatchStatus How the `match_role` job that made this run ended. `null` for a run of the filters alone, or one that never reached an outcome: the worker stopped, or some of those who passed were still being embedded and too few of the rest qualified, which is for the run queued behind it to say.
	MatchStatus *RunStatus `json:"match_status"`

	// MatchedAt When a `match_role` job reranked this run's shortlist and wrote it to the role's matches. `null` for a run of the filters alone, or one whose rerank did not finish.
	MatchedAt *time.Time `json:"matched_at"`

	// Metrics What the matching run took and cost. `null` for a run of the filters alone, and for one whose job did not get to its end.
	Metrics *RunMetrics `json:"metrics"`

	// MinScore The minimum score the run applied (`MATCH_MIN_SCORE` when it ran): a candidate scoring below it is never put in the review queue. `null` when the run scored nobody.
	MinScore *float64 `json:"min_score"`

	// OverlapOn The day the time-zone overlap was worked out for; the role's `starts_on`, or the day of the run when it has none.
	OverlapOn CalendarDate `json:"overlap_on"`

	// Passed Candidates left after the last filter; the length of `candidate_ids`.
	Passed int `json:"passed"`

	// Pool Active candidates when the run started.
	Pool int `json:"pool"`

	// Qualified How many of the run's ranking can be put forward: those who scored at or above `min_score`, not counting a candidate deleted since or one whose match ops rejected or swapped out. `null` when the run scored nobody.
	Qualified *int `json:"qualified"`

	// RequestID The id the run is logged under: that of the `match_role` job attempt that made it or, for a run of the filters alone, of the HTTP request. Every log line either service wrote for the run carries it as `request_id`. `null` on a run recorded before the id was kept.
	RequestID *string `json:"request_id"`

	// RetrievalLimit The most candidates the run could retrieve (`MATCH_RETRIEVAL_SIZE` when it ran). 0 on a run recorded before retrieval existed, which retrieved nothing.
	RetrievalLimit int `json:"retrieval_limit"`

	// Retrieved The shortlist: of those who passed, the most similar to the role, most similar first, at most `retrieval_limit`. Every entry is in `candidate_ids`.
	Retrieved []RetrievedCandidate `json:"retrieved"`

	// RoleEmbedded Whether the role had an embedding to compare with. When false, everyone who passed is in `unranked_ids`: the run is not ready, not empty.
	RoleEmbedded bool `json:"role_embedded"`

	// RoleID A UUID, as text.
	RoleID ID `json:"role_id"`

	// Stages Every filter, in the order applied; each `remaining` is at most the one before it.
	Stages []FilterStage `json:"stages"`

	// TopFilter The must-have that eliminated the most candidates: of the filters after `profile`, the one with the largest `excluded` (the earliest applied, when two tie). `null` when none of them excluded anybody. Filters are applied in order, so each count is of the candidates who got that far.
	TopFilter *FilterStage `json:"top_filter"`

	// UnrankedIds Who passed but could not be compared, by name: their profile or the role had no usable embedding, or the two were embedded by different providers. None of them is in `retrieved`.
	UnrankedIds []ID `json:"unranked_ids"`
}

// FilterStage One filter of a run and what it did to the pool.
type FilterStage struct {
	// Excluded Candidates this filter dropped, of those who reached it.
	Excluded int `json:"excluded"`

	// Filter A hard filter, in the order they are applied.
	Filter FilterName `json:"filter"`

	// Remaining Candidates still in after this filter.
	Remaining int `json:"remaining"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Checks One entry per dependency (`postgres`, `ai`): `ok` or `error: <message>`.
	Checks map[string]string `json:"checks"`
	Status HealthStatus      `json:"status"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus string

// ID A UUID, as text.
type ID = string

// JSONObject A free-form JSON object stored as JSONB.
type JSONObject = RawJSON

// Job One background job in the Postgres-backed queue (the `jobs` table). A
// worker claims a `queued` job whose `run_at` has passed, runs the handler
// for its `kind`, and marks it `succeeded`. A failing attempt puts it back
// to `queued` with `run_at` pushed out by a backoff until `attempts`
// reaches `max_attempts`, when it lands in `failed` with `last_error` set.
type Job struct {
	// Attempts Claims so far, including one in progress.
	Attempts  int       `json:"attempts"`
	CreatedAt time.Time `json:"created_at"`

	// FinishedAt Set when the job reached `succeeded` or `failed`.
	FinishedAt *time.Time `json:"finished_at"`

	// ID A job's id. Jobs are numbered from a sequence, not UUIDs.
	ID JobID `json:"id"`

	// Kind Names the handler that runs it, e.g. `embed_role`, `parse_resume` or `match_role`.
	Kind string `json:"kind"`

	// LastError The most recent failed attempt's error; kept on a `failed` job, cleared on success.
	LastError   *string `json:"last_error"`
	MaxAttempts int     `json:"max_attempts"`

	// Payload Handler-specific input, e.g. `{"role_id": "…"}`.
	Payload JSONObject `json:"payload"`

	// Priority Higher runs first.
	Priority int `json:"priority"`

	// RunAt Not before this time. Retry backoff pushes it into the future.
	RunAt time.Time `json:"run_at"`

	// StartedAt When the current or most recent attempt was claimed.
	StartedAt *time.Time `json:"started_at"`

	// Status `queued` → `running` → `succeeded`, or `running` → `queued` (retry) → … → `failed`.
	Status    JobStatus `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`

	// Worker Id of the worker that last claimed it.
	Worker *string `json:"worker"`
}

// JobCreate defines model for JobCreate.
type JobCreate struct {
	// Kind Must be a kind the worker has a handler for; otherwise a 422 naming the known kinds.
	Kind string `json:"kind"`

	// MaxAttempts Defaults to 3.
	MaxAttempts *int       `json:"max_attempts,omitempty"`
	Payload     JSONObject `json:"payload,omitempty"`

	// Priority Defaults to 0. Higher runs first.
	Priority *int `json:"priority,omitempty"`

	// RunAt Delay the job until this time. Defaults to now.
	RunAt *time.Time `json:"run_at,omitempty"`
}

// JobID A job's id. Jobs are numbered from a sequence, not UUIDs.
type JobID = int64

// JobStatus `queued` → `running` → `succeeded`, or `running` → `queued` (retry) → … → `failed`.
type JobStatus string

// Match defines model for Match.
type Match struct {
	// Breakdown Scoring detail. On a match a `match_role` job wrote: `filter_run_id` (the run it came from), `rank` (the candidate's place in that run's ranking, 1 first), `similarity` (embedding similarity to the role), `rubric_version`, `provider`, `reasons`, and `dimensions`: for each dimension of the rerank rubric the `level` (0 to 4, or null), a sentence of `evidence` and the `quotes` from the candidate's text that back it.
	Breakdown JSONObject `json:"breakdown"`

	// CandidateID A UUID, as text.
	CandidateID ID `json:"candidate_id"`

	// CandidateName Denormalised from the candidate.
	CandidateName string    `json:"candidate_name"`
	CreatedAt     time.Time `json:"created_at"`
	Explanation   string    `json:"explanation"`

	// ID A UUID, as text.
	ID ID `json:"id"`

	// ReleasedAt Set when ops released the match to the employer (`POST /roles/{id}/release`).
	ReleasedAt *time.Time `json:"released_at"`

	// RoleID A UUID, as text.
	RoleID ID `json:"role_id"`

	// RoleTitle Denormalised from the role so a shortlist needs one request.
	RoleTitle string  `json:"role_title"`
	Score     float64 `json:"score"`

	// Status `pending_review` is the review queue: the top of a matching run's ranking, waiting for an ops decision. `proposed` is a match nobody has decided on that is not in the queue: the rest of what a run scored, or one ops wrote by hand. `approved`, `rejected` and `swapped` are ops' decisions, made through the review operations. None of them says anything about what the employer sees; that is `released_at`.
	Status    MatchStatus `json:"status"`
	UpdatedAt time.Time   `json:"updated_at"`
}

// MatchCreate defines model for MatchCreate.
type MatchCreate struct {
	Breakdown JSONObject `json:"breakdown,omitempty"`

	// CandidateID A UUID, as text.
	CandidateID ID      `json:"candidate_id"`
	Explanation *string `json:"explanation,omitempty"`

	// RoleID A UUID, as text.
	RoleID ID      `json:"role_id"`
	Score  float64 `json:"score"`

	// Status `proposed` (the default) or `pending_review`.
	Status *MatchStatus `json:"status,omitempty"`
}

// MatchStatus `pending_review` is the review queue: the top of a matching run's ranking, waiting for an ops decision. `proposed` is a match nobody has decided on that is not in the queue: the rest of what a run scored, or one ops wrote by hand. `approved`, `rejected` and `swapped` are ops' decisions, made through the review operations. None of them says anything about what the employer sees; that is `released_at`.
type MatchStatus string

// MatchUpdate The ops-editable part of a match. Fields not sent keep their value. `status` is not one of them: it changes through the review operations.
type MatchUpdate struct {
	Breakdown JSONObject `json:"breakdown,omitempty"`

	// Explanation `null` clears it to an empty string.
	Explanation *string  `json:"explanation,omitempty"`
	Score       *float64 `json:"score,omitempty"`
}

// Persona The value of the `X-Role` header. Each operation's `x-roles` lists the personas that may call it.
type Persona string

// Profile One structured profile per candidate, with the hard-filter columns promoted out of the JSON.
type Profile struct {
	// Availability What the resume suggests. The filters use `WorkAvailability`, which the candidate supplies.
	Availability  Availability  `json:"availability"`
	AvailableFrom *CalendarDate `json:"available_from"`

	// CandidateID A UUID, as text.
	CandidateID ID `json:"candidate_id"`

	// Certifications Canonical taxonomy ids.
	Certifications []string   `json:"certifications"`
	CreatedAt      time.Time  `json:"created_at"`
	EmbeddedAt     *time.Time `json:"embedded_at"`
	EmbeddingModel *string    `json:"embedding_model"`
	Headline       *string    `json:"headline"`

	// ID A UUID, as text.
	ID ID `json:"id"`

	// Profile The parser's structured extraction (the AI service's `CandidateProfile`).
	Profile JSONObject `json:"profile"`

	// Software Canonical taxonomy ids.
	Software []string `json:"software"`

	// Timezone IANA zone name.
	Timezone        *string   `json:"timezone"`
	UpdatedAt       time.Time `json:"updated_at"`
	YearsExperience *int      `json:"years_experience"`
}

// ProfileInput Body for `PUT …/profile`. Taxonomy lists accept free text and are stored as canonical ids.
type ProfileInput struct {
	// Availability Defaults to `unknown`.
	Availability   *Availability `json:"availability,omitempty"`
	AvailableFrom  *CalendarDate `json:"available_from,omitempty"`
	Certifications []string      `json:"certifications,omitempty"`
	Headline       *string       `json:"headline,omitempty"`
	Profile        JSONObject    `json:"profile,omitempty"`
	Software       []string      `json:"software,omitempty"`

	// Timezone IANA zone name, e.g. `America/Chicago`.
	Timezone        *string `json:"timezone,omitempty"`
	YearsExperience *int    `json:"years_experience,omitempty"`
}

// RetrievedCandidate One candidate of a run's shortlist.
type RetrievedCandidate struct {
	// CandidateID A UUID, as text.
	CandidateID ID `json:"candidate_id"`

	// Similarity Cosine similarity of the profile's embedding to the role's; 1 is the same direction.
	Similarity float64 `json:"similarity"`
}

// ReviewAction What a review event records. Each is written by the review operation of the same name.
type ReviewAction string

// ReviewEvent One ops decision on a match, as recorded when it was made.
type ReviewEvent struct {
	// Action What a review event records. Each is written by the review operation of the same name.
	Action ReviewAction `json:"action"`

	// Actor Who did it, the `X-Actor` of the request.
	Actor string `json:"actor"`

	// CandidateID The candidate of the match the decision was on.
	CandidateID   ID        `json:"candidate_id"`
	CandidateName string    `json:"candidate_name"`
	CreatedAt     time.Time `json:"created_at"`

	// ID Events are numbered in the order they were recorded.
	ID int64 `json:"id"`

	// MatchID A UUID, as text.
	MatchID ID `json:"match_id"`

	// Metadata `from`, the status the match had before an approve, reject or swap; for a swap also `replacement_match_id`.
	Metadata JSONObject `json:"metadata"`
	Reason   *string    `json:"reason"`

	// ReplacementCandidateID For a `swap`, the candidate brought into the queue.
	ReplacementCandidateID   *ID     `json:"replacement_candidate_id"`
	ReplacementCandidateName *string `json:"replacement_candidate_name"`

	// RoleID A UUID, as text.
	RoleID ID `json:"role_id"`
}

// ReviewInput defines model for ReviewInput.
type ReviewInput struct {
	// Reason Recorded on the review event.
	Reason *string `json:"reason,omitempty"`
}

// ReviewQueue A role's matches under review.
type ReviewQueue struct {
	// Approved The `approved` matches, best first. The role can be released when there are exactly two; `released_at` says whether each has been.
	Approved []Match `json:"approved"`

	// Next The next ranked candidate, whom a swap would bring into the queue. `null` when nobody in reserve scores the minimum or more.
	Next *Match `json:"next"`

	// Pending The queue, the `pending_review` matches waiting for a decision, best first.
	Pending []Match `json:"pending"`

	// RoleID A UUID, as text.
	RoleID ID `json:"role_id"`
}

// Role defines model for Role.
type Role struct {
	Company   *string   `json:"company"`
	CreatedAt time.Time `json:"created_at"`

	// Description The raw job description.
	Description    string     `json:"description"`
	EmbeddedAt     *time.Time `json:"embedded_at"`
	EmbeddingModel *string    `json:"embedding_model"`

	// HoursPerWeek Hours a week the role needs; a candidate must offer at least as many. `null` when the role does not ask.
	HoursPerWeek *int `json:"hours_per_week"`

	// ID A UUID, as text.
	ID ID `json:"id"`

	// MinOverlapHours Hours of the role's working day a candidate's working hours must cover; `null` when the role does not ask.
	MinOverlapHours *int `json:"min_overlap_hours"`

	// MinYearsExperience Fewest years of experience the role accepts; `null` when the JD gives no number (a `0` sent in is stored as `null`).
	MinYearsExperience *int     `json:"min_years_experience"`
	MustHaves          []string `json:"must_haves"`
	NiceToHaves        []string `json:"nice_to_haves"`

	// RequiredCertifications Canonical taxonomy ids.
	RequiredCertifications []string `json:"required_certifications"`

	// RequiredSoftware Canonical taxonomy ids.
	RequiredSoftware []string `json:"required_software"`

	// Requirements The parser's structured extraction (the AI service's `RoleRequirements`).
	Requirements JSONObject    `json:"requirements"`
	StartsOn     *CalendarDate `json:"starts_on"`
	Status       RoleStatus    `json:"status"`

	// Timezone IANA zone the role operates in. Its working day is 09:00 to 17:00 there.
	Timezone  *string   `json:"timezone"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
}

// RoleInput Body for creating or updating a role. Every field is optional on the
// wire so a `PUT` can send only what changes; `title` is required when
// creating and may not be nulled.
type RoleInput struct {
	Company *string `json:"company,omitempty"`

	// Description `null` clears it to an empty string.
	Description *string `json:"description,omitempty"`

	// HoursPerWeek Supply it at intake when the JD does not state it; a `0` is stored as `null`.
	HoursPerWeek *int `json:"hours_per_week,omitempty"`

	// MinOverlapHours Needs `timezone`. Supply it at intake when the JD does not state it; a `0` is stored as `null`.
	MinOverlapHours        *int          `json:"min_overlap_hours,omitempty"`
	MinYearsExperience     *int          `json:"min_years_experience,omitempty"`
	MustHaves              []string      `json:"must_haves,omitempty"`
	NiceToHaves            []string      `json:"nice_to_haves,omitempty"`
	RequiredCertifications []string      `json:"required_certifications,omitempty"`
	RequiredSoftware       []string      `json:"required_software,omitempty"`
	Requirements           JSONObject    `json:"requirements,omitempty"`
	StartsOn               *CalendarDate `json:"starts_on,omitempty"`

	// Status Defaults to `open` on create.
	Status   *RoleStatus `json:"status,omitempty"`
	Timezone *string     `json:"timezone,omitempty"`
	Title    *string     `json:"title,omitempty"`
}

// RoleIntake defines model for RoleIntake.
type RoleIntake struct {
	// MatchingJob The `match_role` job queued for the role.
	MatchingJob Job  `json:"matching_job"`
	Role        Role `json:"role"`
}

// RoleIntakeInput defines model for RoleIntakeInput.
type RoleIntakeInput struct {
	// Company Overrides the company the parser finds.
	Company *string `json:"company,omitempty"`

	// Description The job description as pasted, up to 60,000 characters.
	Description string `json:"description"`

	// Title Overrides the title the parser finds; required when the job description names none.
	Title *string `json:"title,omitempty"`
}

// RoleMatchState Where a role's matching stands. `ready`: at least two matches are released. `needs_attention` (ops only): not ready, and the latest matching run could not deliver two profiles. `in_review`: anything else, and all an employer is told until the role is `ready`.
type RoleMatchState string

// RoleMatchStatus Where a role's matching stands, as the caller may see it.
type RoleMatchStatus struct {
	// Released Matches released to the employer.
	Released int `json:"released"`

	// RoleID A UUID, as text.
	RoleID ID `json:"role_id"`

	// Run The latest matching run with an outcome: its `attention_reason`, the funnel and `top_filter`. Always `null` for an employer, and for ops when no run has finished.
	Run *FilterRun `json:"run"`

	// Status Where a role's matching stands. `ready`: at least two matches are released. `needs_attention` (ops only): not ready, and the latest matching run could not deliver two profiles. `in_review`: anything else, and all an employer is told until the role is `ready`.
	Status RoleMatchState `json:"status"`
}

// RoleStatus defines model for RoleStatus.
type RoleStatus string

// RunMetrics What one matching run (a `match_role` job attempt) took and cost: the time of each stage, and what the rerank spent on the chat model as the AI service reported it. A `/rerank` call that failed reports nothing, so the model figures of a run that needs attention as `ai_failed` cover only the batches that answered.
type RunMetrics struct {
	// CacheHits Completions the AI service replayed from its response cache instead; they cost nothing.
	CacheHits int `json:"cache_hits"`

	// Candidates Candidates sent to the rerank.
	Candidates int `json:"candidates"`

	// EstimatedCostUsd The tokens at the model's list price, in US dollars. 0 for a run answered from the cache or by the `fake` provider; `null` when the AI service knows no price for the model.
	EstimatedCostUsd *float64 `json:"estimated_cost_usd"`

	// InputTokens Prompt tokens of `llm_calls`, as the provider counted them.
	InputTokens int `json:"input_tokens"`

	// LlmCalls Chat-model completions that reached the provider, over all batches. More than `rerank_calls` when an answer had to be sent back for correction; fewer when answers were replayed from the cache.
	LlmCalls int `json:"llm_calls"`

	// Model The chat model the AI service ran the rerank on; `null` when no batch answered.
	Model *string `json:"model"`

	// OutputTokens Output tokens of `llm_calls`, the model's thinking included.
	OutputTokens int `json:"output_tokens"`

	// RerankCalls Requests to the AI service's `/rerank`, one per batch of the shortlist; they run at once.
	RerankCalls int `json:"rerank_calls"`

	// StageMs How long each stage of a matching run took, in milliseconds. A stage the run did not reach is 0.
	StageMs RunStageMs `json:"stage_ms"`

	// TotalMs The whole run, from the job reading its role to the last write, in milliseconds.
	TotalMs int `json:"total_ms"`
}

// RunStageMs How long each stage of a matching run took, in milliseconds. A stage the run did not reach is 0.
type RunStageMs struct {
	// Filter The hard filters and the retrieval by embedding, which are one statement.
	Filter int `json:"filter"`

	// Persist Writing the ranking to `matches` and the outcome to the run.
	Persist int `json:"persist"`

	// Rerank The AI service's `/rerank`, all batches; they run at once, so this is the slowest of them.
	Rerank int `json:"rerank"`

	// Texts Reading the role and the shortlisted candidates' text for the rerank.
	Texts int `json:"texts"`
}

// RunStatus How a matching run ended. `matched`: at least two candidates passed the hard filters and scored at or above the minimum. `needs_attention`: the run could not deliver two profiles (see `AttentionReason`).
type RunStatus string

// SwapResult defines model for SwapResult.
type SwapResult struct {
	// Replacement The next ranked match, now `pending_review`.
	Replacement Match `json:"replacement"`

	// Swapped The match taken out, now `swapped`.
	Swapped Match `json:"swapped"`
}

// WorkAvailability When and where the candidate can work, as the candidate gave it. All four answers or none.
type WorkAvailability struct {
	// AvailableFrom The earliest day the candidate can start.
	AvailableFrom CalendarDate `json:"available_from"`

	// CandidateID A UUID, as text.
	CandidateID  ID        `json:"candidate_id"`
	CreatedAt    time.Time `json:"created_at"`
	HoursPerWeek int       `json:"hours_per_week"`

	// Timezone IANA zone name, e.g. `America/Chicago`.
	Timezone  string    `json:"timezone"`
	UpdatedAt time.Time `json:"updated_at"`

	// WorkEnd End of the working hours. At or before `work_start` means they run past midnight.
	WorkEnd ClockTime `json:"work_end"`

	// WorkStart Start of the candidate's working hours, in their own time zone.
	WorkStart ClockTime `json:"work_start"`
}

// WorkAvailabilityInput Body for `PUT …/availability`. Every field is required; they are optional on the wire so a missing one is a 422 naming it.
type WorkAvailabilityInput struct {
	// AvailableFrom A calendar day, `YYYY-MM-DD`.
	AvailableFrom *CalendarDate `json:"available_from,omitempty"`
	HoursPerWeek  *int          `json:"hours_per_week,omitempty"`
	Timezone      *string       `json:"timezone,omitempty"`

	// WorkEnd A time of day on a 24-hour clock, `HH:MM`.
	WorkEnd *ClockTime `json:"work_end,omitempty"`

	// WorkStart A time of day on a 24-hour clock, `HH:MM`.
	WorkStart *ClockTime `json:"work_start,omitempty"`
}

// Limit defines model for Limit.
type Limit = int

// Offset defines model for Offset.
type Offset = int

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ValidationFailed defines model for ValidationFailed.
type ValidationFailed = Error

// actorContextKey is the context key for actor security scheme
type actorContextKey string

// roleContextKey is the context key for role security scheme
type roleContextKey string

// ListCandidatesParams defines parameters for ListCandidates.
type ListCandidatesParams struct {
	Status *CandidateStatus `form:"status,omitempty" json:"status,omitempty"`

	// Limit Page size; default 50, max 200.
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	Status *JobStatus `form:"status,omitempty" json:"status,omitempty"`
	Kind   *string    `form:"kind,omitempty" json:"kind,omitempty"`

	// Limit Page size; default 50, max 200.
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListMatchesParams defines parameters for ListMatches.
type ListMatchesParams struct {
	RoleID      *ID          `form:"role_id,omitempty" json:"role_id,omitempty"`
	CandidateID *ID          `form:"candidate_id,omitempty" json:"candidate_id,omitempty"`
	Status      *MatchStatus `form:"status,omitempty" json:"status,omitempty"`

	// Limit Page size; default 50, max 200.
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListRolesParams defines parameters for ListRoles.
type ListRolesParams struct {
	Status *RoleStatus `form:"status,omitempty" json:"status,omitempty"`

	// Company Exact match.
	Company *string `form:"company,omitempty" json:"company,omitempty"`

	// Limit Page size; default 50, max 200.
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListRoleAvailabilityParams defines parameters for ListRoleAvailability.
type ListRoleAvailabilityParams struct {
	// Limit Page size; default 50, max 200.
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListRoleFilterRunsParams defines parameters for ListRoleFilterRuns.
type ListRoleFilterRunsParams struct {
	// Limit Page size; default 50, max 200.
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListReviewEventsParams defines parameters for ListReviewEvents.
type ListReviewEventsParams struct {
	// Limit Page size; default 50, max 200.
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateCandidateJSONRequestBody defines body for CreateCandidate for application/json ContentType.
type CreateCandidateJSONRequestBody = CandidateInput

// UpdateCandidateJSONRequestBody defines body for UpdateCandidate for application/json ContentType.
type UpdateCandidateJSONRequestBody = CandidateInput

// PutAvailabilityJSONRequestBody defines body for PutAvailability for application/json ContentType.
type PutAvailabilityJSONRequestBody = WorkAvailabilityInput

// PutProfileJSONRequestBody defines body for PutProfile for application/json ContentType.
type PutProfileJSONRequestBody = ProfileInput

// CreateJobJSONRequestBody defines body for CreateJob for application/json ContentType.
type CreateJobJSONRequestBody = JobCreate

// CreateMatchJSONRequestBody defines body for CreateMatch for application/json ContentType.
type CreateMatchJSONRequestBody = MatchCreate

// UpdateMatchJSONRequestBody defines body for UpdateMatch for application/json ContentType.
type UpdateMatchJSONRequestBody = MatchUpdate

// ApproveMatchJSONRequestBody defines body for ApproveMatch for application/json ContentType.
type ApproveMatchJSONRequestBody = ReviewInput

// RejectMatchJSONRequestBody defines body for RejectMatch for application/json ContentType.
type RejectMatchJSONRequestBody = ReviewInput

// SwapMatchJSONRequestBody defines body for SwapMatch for application/json ContentType.
type SwapMatchJSONRequestBody = ReviewInput

// UnreleaseMatchJSONRequestBody defines body for UnreleaseMatch for application/json ContentType.
type UnreleaseMatchJSONRequestBody = ReviewInput

// CreateRoleJSONRequestBody defines body for CreateRole for application/json ContentType.
type CreateRoleJSONRequestBody = RoleInput

// IntakeRoleJSONRequestBody defines body for IntakeRole for application/json ContentType.
type IntakeRoleJSONRequestBody = RoleIntakeInput

// UpdateRoleJSONRequestBody defines body for UpdateRole for application/json ContentType.
type UpdateRoleJSONRequestBody = RoleInput

// ReleaseRoleJSONRequestBody defines body for ReleaseRole for application/json ContentType.
type ReleaseRoleJSONRequestBody = ReviewInput
