// Package contract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package contract

import (
	"time"
)

const (
	RoleScopes roleContextKey = "role.Scopes"
)

// Defines values for Availability.
const (
	AvailabilityImmediate   Availability = "immediate"
	AvailabilityOneMonth    Availability = "one_month"
	AvailabilityTwoWeeks    Availability = "two_weeks"
	AvailabilityUnavailable Availability = "unavailable"
	AvailabilityUnknown     Availability = "unknown"
)

// Valid indicates whether the value is a known member of the Availability enum.
func (e Availability) Valid() bool {
	switch e {
	case AvailabilityImmediate:
		return true
	case AvailabilityOneMonth:
		return true
	case AvailabilityTwoWeeks:
		return true
	case AvailabilityUnavailable:
		return true
	case AvailabilityUnknown:
		return true
	default:
		return false
	}
}

// Defines values for CandidateStatus.
const (
	CandidateStatusActive   CandidateStatus = "active"
	CandidateStatusArchived CandidateStatus = "archived"
)

// Valid indicates whether the value is a known member of the CandidateStatus enum.
func (e CandidateStatus) Valid() bool {
	switch e {
	case CandidateStatusActive:
		return true
	case CandidateStatusArchived:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusDegraded HealthStatus = "degraded"
	HealthStatusOk       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusDegraded:
		return true
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for JobStatus.
const (
	JobStatusFailed    JobStatus = "failed"
	JobStatusQueued    JobStatus = "queued"
	JobStatusRunning   JobStatus = "running"
	JobStatusSucceeded JobStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case JobStatusFailed:
		return true
	case JobStatusQueued:
		return true
	case JobStatusRunning:
		return true
	case JobStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for MatchStatus.
const (
	MatchStatusApproved MatchStatus = "approved"
	MatchStatusProposed MatchStatus = "proposed"
	MatchStatusRejected MatchStatus = "rejected"
	MatchStatusSwapped  MatchStatus = "swapped"
)

// Valid indicates whether the value is a known member of the MatchStatus enum.
func (e MatchStatus) Valid() bool {
	switch e {
	case MatchStatusApproved:
		return true
	case MatchStatusProposed:
		return true
	case MatchStatusRejected:
		return true
	case MatchStatusSwapped:
		return true
	default:
		return false
	}
}

// Defines values for Persona.
const (
	PersonaEmployer Persona = "employer"
	PersonaOps      Persona = "ops"
	PersonaTalent   Persona = "talent"
)

// Valid indicates whether the value is a known member of the Persona enum.
func (e Persona) Valid() bool {
	switch e {
	case PersonaEmployer:
		return true
	case PersonaOps:
		return true
	case PersonaTalent:
		return true
	default:
		return false
	}
}

// Defines values for RoleStatus.
const (
	RoleStatusClosed RoleStatus = "closed"
	RoleStatusFilled RoleStatus = "filled"
	RoleStatusOpen   RoleStatus = "open"
)

// Valid indicates whether the value is a known member of the RoleStatus enum.
func (e RoleStatus) Valid() bool {
	switch e {
	case RoleStatusClosed:
		return true
	case RoleStatusFilled:
		return true
	case RoleStatusOpen:
		return true
	default:
		return false
	}
}

// Availability defines model for Availability.
type Availability string

// CalendarDate A calendar day, `YYYY-MM-DD`.
type CalendarDate = Date

// Candidate defines model for Candidate.
type Candidate struct {
	CreatedAt time.Time `json:"created_at"`
	Email     *string   `json:"email"`
	FullName  string    `json:"full_name"`

	// ID A UUID, as text.
	ID         ID      `json:"id"`
	Location   *string `json:"location"`
	Phone      *string `json:"phone"`
	ResumeText string  `json:"resume_text"`

	// Source Where the record came from; `self` when talent created it.
	Source    *string         `json:"source"`
	Status    CandidateStatus `json:"status"`
	UpdatedAt time.Time       `json:"updated_at"`
}

// CandidateInput Body for creating or updating a candidate. Every field is optional on
// the wire so a `PUT` can send only what changes; `full_name` is required
// when creating and may not be nulled. `null` clears an optional field.
type CandidateInput struct {
	Email    *string `json:"email,omitempty"`
	FullName *string `json:"full_name,omitempty"`
	Location *string `json:"location,omitempty"`
	Phone    *string `json:"phone,omitempty"`

	// ResumeText `null` clears it to an empty string.
	ResumeText *string `json:"resume_text,omitempty"`
	Source     *string `json:"source,omitempty"`

	// Status Defaults to `active` on create.
	Status *CandidateStatus `json:"status,omitempty"`
}

// CandidateStatus defines model for CandidateStatus.
type CandidateStatus string

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`

	// Fields Per-field messages on a 422.
	Fields *map[string]string `json:"fields,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Checks One entry per dependency (`postgres`, `ai`): `ok` or `error: <message>`.
	Checks map[string]string `json:"checks"`
	Status HealthStatus      `json:"status"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus string

// ID A UUID, as text.
type ID = string

// JSONObject A free-form JSON object stored as JSONB.
type JSONObject = RawJSON

// Job One background job in the Postgres-backed queue (the `jobs` table). A
// worker claims a `queued` job whose `run_at` has passed, runs the handler
// for its `kind`, and marks it `succeeded`. A failing attempt puts it back
// to `queued` with `run_at` pushed out by a backoff until `attempts`
// reaches `max_attempts`, when it lands in `failed` with `last_error` set.
type Job struct {
	// Attempts Claims so far, including one in progress.
	Attempts  int       `json:"attempts"`
	CreatedAt time.Time `json:"created_at"`

	// FinishedAt Set when the job reached `succeeded` or `failed`.
	FinishedAt *time.Time `json:"finished_at"`

	// ID A job's id. Jobs are numbered from a sequence, not UUIDs.
	ID JobID `json:"id"`

	// Kind Names the handler that runs it, e.g. `embed_role` or `parse_resume`.
	Kind string `json:"kind"`

	// LastError The most recent failed attempt's error; kept on a `failed` job, cleared on success.
	LastError   *string `json:"last_error"`
	MaxAttempts int     `json:"max_attempts"`

	// Payload Handler-specific input, e.g. `{"role_id": "…"}`.
	Payload JSONObject `json:"payload"`

	// Priority Higher runs first.
	Priority int `json:"priority"`

	// RunAt Not before this time. Retry backoff pushes it into the future.
	RunAt time.Time `json:"run_at"`

	// StartedAt When the current or most recent attempt was claimed.
	StartedAt *time.Time `json:"started_at"`

	// Status `queued` → `running` → `succeeded`, or `running` → `queued` (retry) → … → `failed`.
	Status    JobStatus `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`

	// Worker Id of the worker that last claimed it.
	Worker *string `json:"worker"`
}

// JobCreate defines model for JobCreate.
type JobCreate struct {
	// Kind Must be a kind the worker has a handler for; otherwise a 422 naming the known kinds.
	Kind string `json:"kind"`

	// MaxAttempts Defaults to 3.
	MaxAttempts *int       `json:"max_attempts,omitempty"`
	Payload     JSONObject `json:"payload,omitempty"`

	// Priority Defaults to 0. Higher runs first.
	Priority *int `json:"priority,omitempty"`

	// RunAt Delay the job until this time. Defaults to now.
	RunAt *time.Time `json:"run_at,omitempty"`
}

// JobID A job's id. Jobs are numbered from a sequence, not UUIDs.
type JobID = int64

// JobStatus `queued` → `running` → `succeeded`, or `running` → `queued` (retry) → … → `failed`.
type JobStatus string

// Match defines model for Match.
type Match struct {
	// Breakdown Per-criterion scoring detail.
	Breakdown JSONObject `json:"breakdown"`

	// CandidateID A UUID, as text.
	CandidateID ID `json:"candidate_id"`

	// CandidateName Denormalised from the candidate.
	CandidateName string    `json:"candidate_name"`
	CreatedAt     time.Time `json:"created_at"`
	Explanation   string    `json:"explanation"`

	// ID A UUID, as text.
	ID ID `json:"id"`

	// ReleasedAt Set when ops released the match to the employer.
	ReleasedAt *time.Time `json:"released_at"`

	// RoleID A UUID, as text.
	RoleID ID `json:"role_id"`

	// RoleTitle Denormalised from the role so a shortlist needs one request.
	RoleTitle string      `json:"role_title"`
	Score     float64     `json:"score"`
	Status    MatchStatus `json:"status"`
	UpdatedAt time.Time   `json:"updated_at"`
}

// MatchCreate defines model for MatchCreate.
type MatchCreate struct {
	Breakdown JSONObject `json:"breakdown,omitempty"`

	// CandidateID A UUID, as text.
	CandidateID ID      `json:"candidate_id"`
	Explanation *string `json:"explanation,omitempty"`

	// RoleID A UUID, as text.
	RoleID ID      `json:"role_id"`
	Score  float64 `json:"score"`

	// Status Defaults to `proposed`.
	Status *MatchStatus `json:"status,omitempty"`
}

// MatchStatus defines model for MatchStatus.
type MatchStatus string

// MatchUpdate The ops-editable part of a match. Fields not sent keep their value.
type MatchUpdate struct {
	Breakdown JSONObject `json:"breakdown,omitempty"`

	// Explanation `null` clears it to an empty string.
	Explanation *string      `json:"explanation,omitempty"`
	Score       *float64     `json:"score,omitempty"`
	Status      *MatchStatus `json:"status,omitempty"`
}

// Persona The value of the `X-Role` header. Each operation's `x-roles` lists the personas that may call it.
type Persona string

// Profile One structured profile per candidate, with the hard-filter columns promoted out of the JSON.
type Profile struct {
	Availability  Availability  `json:"availability"`
	AvailableFrom *CalendarDate `json:"available_from"`

	// CandidateID A UUID, as text.
	CandidateID ID `json:"candidate_id"`

	// Certifications Canonical taxonomy ids.
	Certifications []string   `json:"certifications"`
	CreatedAt      time.Time  `json:"created_at"`
	EmbeddedAt     *time.Time `json:"embedded_at"`
	EmbeddingModel *string    `json:"embedding_model"`
	Headline       *string    `json:"headline"`

	// ID A UUID, as text.
	ID ID `json:"id"`

	// Profile The parser's structured extraction (the AI service's `CandidateProfile`).
	Profile JSONObject `json:"profile"`

	// Software Canonical taxonomy ids.
	Software []string `json:"software"`

	// Timezone IANA zone name.
	Timezone        *string   `json:"timezone"`
	UpdatedAt       time.Time `json:"updated_at"`
	YearsExperience *int      `json:"years_experience"`
}

// ProfileInput Body for `PUT …/profile`. Taxonomy lists accept free text and are stored as canonical ids.
type ProfileInput struct {
	// Availability Defaults to `unknown`.
	Availability   *Availability `json:"availability,omitempty"`
	AvailableFrom  *CalendarDate `json:"available_from,omitempty"`
	Certifications []string      `json:"certifications,omitempty"`
	Headline       *string       `json:"headline,omitempty"`
	Profile        JSONObject    `json:"profile,omitempty"`
	Software       []string      `json:"software,omitempty"`

	// Timezone IANA zone name, e.g. `America/Chicago`.
	Timezone        *string `json:"timezone,omitempty"`
	YearsExperience *int    `json:"years_experience,omitempty"`
}

// ReleaseInput defines model for ReleaseInput.
type ReleaseInput struct {
	// Reason Recorded on the review event.
	Reason *string `json:"reason,omitempty"`
}

// Role defines model for Role.
type Role struct {
	Company   *string   `json:"company"`
	CreatedAt time.Time `json:"created_at"`

	// Description The raw job description.
	Description    string     `json:"description"`
	EmbeddedAt     *time.Time `json:"embedded_at"`
	EmbeddingModel *string    `json:"embedding_model"`

	// ID A UUID, as text.
	ID ID `json:"id"`

	// MinYearsExperience Fewest years of experience the role accepts; `null` when the JD gives no number (a `0` sent in is stored as `null`).
	MinYearsExperience *int     `json:"min_years_experience"`
	MustHaves          []string `json:"must_haves"`
	NiceToHaves        []string `json:"nice_to_haves"`

	// RequiredCertifications Canonical taxonomy ids.
	RequiredCertifications []string `json:"required_certifications"`

	// RequiredSoftware Canonical taxonomy ids.
	RequiredSoftware []string `json:"required_software"`

	// Requirements The parser's structured extraction (the AI service's `RoleRequirements`).
	Requirements JSONObject    `json:"requirements"`
	StartsOn     *CalendarDate `json:"starts_on"`
	Status       RoleStatus    `json:"status"`
	Timezone     *string       `json:"timezone"`
	Title        string        `json:"title"`
	UpdatedAt    time.Time     `json:"updated_at"`
}

// RoleInput Body for creating or updating a role. Every field is optional on the
// wire so a `PUT` can send only what changes; `title` is required when
// creating and may not be nulled.
type RoleInput struct {
	Company *string `json:"company,omitempty"`

	// Description `null` clears it to an empty string.
	Description            *string       `json:"description,omitempty"`
	MinYearsExperience     *int          `json:"min_years_experience,omitempty"`
	MustHaves              []string      `json:"must_haves,omitempty"`
	NiceToHaves            []string      `json:"nice_to_haves,omitempty"`
	RequiredCertifications []string      `json:"required_certifications,omitempty"`
	RequiredSoftware       []string      `json:"required_software,omitempty"`
	Requirements           JSONObject    `json:"requirements,omitempty"`
	StartsOn               *CalendarDate `json:"starts_on,omitempty"`

	// Status Defaults to `open` on create.
	Status   *RoleStatus `json:"status,omitempty"`
	Timezone *string     `json:"timezone,omitempty"`
	Title    *string     `json:"title,omitempty"`
}

// RoleStatus defines model for RoleStatus.
type RoleStatus string

// Limit defines model for Limit.
type Limit = int

// Offset defines model for Offset.
type Offset = int

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ValidationFailed defines model for ValidationFailed.
type ValidationFailed = Error

// actorContextKey is the context key for actor security scheme
type actorContextKey string

// roleContextKey is the context key for role security scheme
type roleContextKey string

// ListCandidatesParams defines parameters for ListCandidates.
type ListCandidatesParams struct {
	Status *CandidateStatus `form:"status,omitempty" json:"status,omitempty"`

	// Limit Page size; default 50, max 200.
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	Status *JobStatus `form:"status,omitempty" json:"status,omitempty"`
	Kind   *string    `form:"kind,omitempty" json:"kind,omitempty"`

	// Limit Page size; default 50, max 200.
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListMatchesParams defines parameters for ListMatches.
type ListMatchesParams struct {
	RoleID      *ID          `form:"role_id,omitempty" json:"role_id,omitempty"`
	CandidateID *ID          `form:"candidate_id,omitempty" json:"candidate_id,omitempty"`
	Status      *MatchStatus `form:"status,omitempty" json:"status,omitempty"`

	// Limit Page size; default 50, max 200.
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListRolesParams defines parameters for ListRoles.
type ListRolesParams struct {
	Status *RoleStatus `form:"status,omitempty" json:"status,omitempty"`

	// Company Exact match.
	Company *string `form:"company,omitempty" json:"company,omitempty"`

	// Limit Page size; default 50, max 200.
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateCandidateJSONRequestBody defines body for CreateCandidate for application/json ContentType.
type CreateCandidateJSONRequestBody = CandidateInput

// UpdateCandidateJSONRequestBody defines body for UpdateCandidate for application/json ContentType.
type UpdateCandidateJSONRequestBody = CandidateInput

// PutProfileJSONRequestBody defines body for PutProfile for application/json ContentType.
type PutProfileJSONRequestBody = ProfileInput

// CreateJobJSONRequestBody defines body for CreateJob for application/json ContentType.
type CreateJobJSONRequestBody = JobCreate

// CreateMatchJSONRequestBody defines body for CreateMatch for application/json ContentType.
type CreateMatchJSONRequestBody = MatchCreate

// UpdateMatchJSONRequestBody defines body for UpdateMatch for application/json ContentType.
type UpdateMatchJSONRequestBody = MatchUpdate

// ReleaseMatchJSONRequestBody defines body for ReleaseMatch for application/json ContentType.
type ReleaseMatchJSONRequestBody = ReleaseInput

// UnreleaseMatchJSONRequestBody defines body for UnreleaseMatch for application/json ContentType.
type UnreleaseMatchJSONRequestBody = ReleaseInput

// CreateRoleJSONRequestBody defines body for CreateRole for application/json ContentType.
type CreateRoleJSONRequestBody = RoleInput

// UpdateRoleJSONRequestBody defines body for UpdateRole for application/json ContentType.
type UpdateRoleJSONRequestBody = RoleInput
