/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness of the API and its dependencies */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List candidates */
        get: operations["listCandidates"];
        put?: never;
        /**
         * Create a candidate
         * @description Talent-created candidates are marked `source: self` unless a source is given.
         */
        post: operations["createCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * Fetch a candidate
         * @description Talent may only read their own record (`X-Actor` = id); another id is a 404.
         */
        get: operations["getCandidate"];
        /**
         * Update a candidate
         * @description Replaces the fields sent and keeps the rest. Talent may only update their own record.
         */
        put: operations["updateCandidate"];
        post?: never;
        /** Delete a candidate */
        delete: operations["deleteCandidate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Fetch a candidate's structured profile */
        get: operations["getProfile"];
        /**
         * Create or replace a candidate's profile
         * @description Replaces the whole profile. Omitted lists become empty and an omitted
         *     availability becomes `unknown`. Re-saving identical content keeps the
         *     stored embedding; a change to the text it was derived from clears it.
         */
        put: operations["putProfile"];
        post?: never;
        /** Delete a candidate's profile */
        delete: operations["deleteProfile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a resume and queue its parsing
         * @description Talent intake. The request body is the file itself (not multipart): a
         *     PDF, or a DOCX. What the file is is read from its content, not from
         *     `Content-Type`. Its text is extracted in the request and stored as the
         *     candidate's `resume_text`, and a `parse_resume` job is queued; the
         *     response is that job, whose `id` is what to poll. The worker sends the
         *     text to the AI service's `/parse-resume`, writes the result as the
         *     candidate's profile (replacing any profile already there) and embeds
         *     it. Poll `GET /candidates/{id}/resume/job` (or, as ops,
         *     `GET /jobs/{id}`) until `status` is `succeeded`, then read
         *     `GET /candidates/{id}/profile`.
         *
         *     Uploading again while the job is still queued replaces the text and
         *     returns the same job. Talent may only upload to their own record.
         */
        post: operations["uploadResume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}/resume/job": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * Status of the candidate's most recent resume parse
         * @description The newest `parse_resume` job for the candidate: the same object
         *     `GET /jobs/{id}` returns, readable by the talent who uploaded. The
         *     profile is ready when `status` is `succeeded`; on `failed`,
         *     `last_error` says why. A 404 when no resume was ever uploaded.
         */
        get: operations["getResumeJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * Fetch what the candidate said about when and where they can work
         * @description A 404 until the candidate has supplied it; such a candidate is excluded from matching.
         */
        get: operations["getAvailability"];
        /**
         * Set or edit the candidate's time zone, working hours, hours per week and start date
         * @description Availability and time-zone overlap are hard filters that a resume
         *     cannot answer, so the candidate supplies them, here. All four are
         *     required and the body replaces whatever was stored. Parsing a resume
         *     (again) never changes them. Talent may only set their own.
         */
        put: operations["putAvailability"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List roles
         * @description Talent only ever receives open roles; a `status` filter other than `open` returns an empty list for talent.
         */
        get: operations["listRoles"];
        put?: never;
        /** Create a role */
        post: operations["createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * Fetch a role
         * @description A role that is not open is a 404 for talent.
         */
        get: operations["getRole"];
        /**
         * Update a role
         * @description Replaces the fields sent and keeps the rest. Changing the description clears the stored embedding.
         */
        put: operations["updateRole"];
        post?: never;
        /** Delete a role */
        delete: operations["deleteRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{id}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * Which active candidates pass the role's availability and time-zone filters
         * @description One entry per active candidate, by name, each with whether it passes
         *     and, when it does not, why. A candidate who has not supplied their
         *     availability never passes, whatever the role asks for. Otherwise the
         *     candidate must be able to start by `starts_on`, offer at least the
         *     role's `hours_per_week`, and have working hours that cover at least
         *     `min_overlap_hours` of the role's working day (09:00 to 17:00 in the
         *     role's `timezone`, on the role's `starts_on`, or on the day of the
         *     request when it has none). A requirement the role leaves null is not
         *     checked.
         */
        get: operations["listRoleAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List matches
         * @description Ops sees every match. Employers see released matches only. Talent sees
         *     released matches for their own candidate only (`X-Actor` = candidate id);
         *     a `candidate_id` filter naming someone else returns an empty list.
         */
        get: operations["listMatches"];
        put?: never;
        /**
         * Propose a match between a role and a candidate
         * @description A candidate who has not supplied their availability (`PUT /candidates/{id}/availability`) cannot be matched; that is a 422 on `candidate_id`.
         */
        post: operations["createMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * Fetch a match
         * @description An unreleased match is a 404 for employers and talent, never a 403.
         */
        get: operations["getMatch"];
        /**
         * Edit a match's review fields
         * @description The (role, candidate) pair is immutable; sending `role_id` or `candidate_id` is a 422.
         */
        put: operations["updateMatch"];
        post?: never;
        /**
         * Delete a match
         * @description A match with review history cannot be deleted (409).
         */
        delete: operations["deleteMatch"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Release a match to the employer
         * @description Sets `released_at` and records a `release` review event with the `X-Actor` value. Releasing an already released match is a no-op.
         */
        post: operations["releaseMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{id}/unrelease": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Withdraw a released match
         * @description Clears `released_at` and records an `unrelease` review event. A no-op on an unreleased match.
         */
        post: operations["unreleaseMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List background jobs */
        get: operations["listJobs"];
        put?: never;
        /**
         * Enqueue a background job
         * @description Adds a job to the Postgres-backed queue. `kind` must be one the worker
         *     has a handler for (`embed_role`, `embed_profile`, `parse_resume`); anything else is a
         *     422 naming the known kinds. If an identical job (same `kind` and
         *     `payload`) is already queued, that job is returned with a 200 instead
         *     of adding a duplicate. The worker picks the job up within its poll
         *     interval; poll `GET /jobs/{id}` until `status` is `succeeded` or `failed`.
         */
        post: operations["createJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        /**
         * Get a background job
         * @description What the UI polls. A job is finished when `status` is `succeeded` or `failed`; a failed job carries the last attempt's error in `last_error`.
         */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description A UUID, as text.
         * @example 11111111-0000-0000-0000-000000000001
         */
        Id: string;
        /**
         * Format: int64
         * @description A job's id. Jobs are numbered from a sequence, not UUIDs.
         * @example 42
         */
        JobId: number;
        /**
         * Format: date
         * @description A calendar day, `YYYY-MM-DD`.
         * @example 2026-10-14
         */
        CalendarDate: string;
        /** @description A free-form JSON object stored as JSONB. */
        JSONObject: {
            [key: string]: unknown;
        };
        /** @enum {string} */
        CandidateStatus: "active" | "archived";
        /** @enum {string} */
        RoleStatus: "open" | "filled" | "closed";
        /** @enum {string} */
        MatchStatus: "proposed" | "approved" | "rejected" | "swapped";
        /**
         * @description `queued` → `running` → `succeeded`, or `running` → `queued` (retry) → … → `failed`.
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed";
        /**
         * @description What the resume suggests. The filters use `WorkAvailability`, which the candidate supplies.
         * @enum {string}
         */
        Availability: "immediate" | "two_weeks" | "one_month" | "unavailable" | "unknown";
        /**
         * @description A time of day on a 24-hour clock, `HH:MM`.
         * @example 09:00
         */
        ClockTime: string;
        /** @enum {string} */
        HealthStatus: "ok" | "degraded";
        /**
         * @description The value of the `X-Role` header. Each operation's `x-roles` lists the personas that may call it.
         * @enum {string}
         */
        Persona: "talent" | "employer" | "ops";
        Error: {
            /** @example validation failed */
            error: string;
            /** @description Per-field messages on a 422. */
            fields?: {
                [key: string]: string;
            };
        };
        HealthResponse: {
            status: components["schemas"]["HealthStatus"];
            /** @description One entry per dependency (`postgres`, `ai`): `ok` or `error: <message>`. */
            checks: {
                [key: string]: string;
            };
        };
        Candidate: {
            id: components["schemas"]["Id"];
            full_name: string;
            email: string | null;
            phone: string | null;
            location: string | null;
            resume_text: string;
            /** @description Where the record came from; `self` when talent created it. */
            source: string | null;
            status: components["schemas"]["CandidateStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description Body for creating or updating a candidate. Every field is optional on
         *     the wire so a `PUT` can send only what changes; `full_name` is required
         *     when creating and may not be nulled. `null` clears an optional field.
         */
        CandidateInput: {
            full_name?: string;
            email?: string | null;
            phone?: string | null;
            location?: string | null;
            /** @description `null` clears it to an empty string. */
            resume_text?: string | null;
            source?: string | null;
            /** @description Defaults to `active` on create. */
            status?: components["schemas"]["CandidateStatus"];
        };
        /** @description One structured profile per candidate, with the hard-filter columns promoted out of the JSON. */
        Profile: {
            id: components["schemas"]["Id"];
            candidate_id: components["schemas"]["Id"];
            /** @description The parser's structured extraction (the AI service's `CandidateProfile`). */
            profile: components["schemas"]["JSONObject"];
            headline: string | null;
            years_experience: number | null;
            /** @description Canonical taxonomy ids. */
            certifications: string[];
            /** @description Canonical taxonomy ids. */
            software: string[];
            availability: components["schemas"]["Availability"];
            available_from: components["schemas"]["CalendarDate"] | null;
            /** @description IANA zone name. */
            timezone: string | null;
            embedding_model: string | null;
            /** Format: date-time */
            embedded_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Body for `PUT …/profile`. Taxonomy lists accept free text and are stored as canonical ids. */
        ProfileInput: {
            profile?: components["schemas"]["JSONObject"];
            headline?: string | null;
            years_experience?: number | null;
            certifications?: string[];
            software?: string[];
            /** @description Defaults to `unknown`. */
            availability?: components["schemas"]["Availability"];
            available_from?: components["schemas"]["CalendarDate"] | null;
            /** @description IANA zone name, e.g. `America/Chicago`. */
            timezone?: string | null;
        };
        /** @description When and where the candidate can work, as the candidate gave it. All four answers or none. */
        WorkAvailability: {
            candidate_id: components["schemas"]["Id"];
            /** @description IANA zone name, e.g. `America/Chicago`. */
            timezone: string;
            /** @description Start of the candidate's working hours, in their own time zone. */
            work_start: components["schemas"]["ClockTime"];
            /** @description End of the working hours. At or before `work_start` means they run past midnight. */
            work_end: components["schemas"]["ClockTime"];
            hours_per_week: number;
            /** @description The earliest day the candidate can start. */
            available_from: components["schemas"]["CalendarDate"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Body for `PUT …/availability`. Every field is required; they are optional on the wire so a missing one is a 422 naming it. */
        WorkAvailabilityInput: {
            timezone?: string;
            work_start?: components["schemas"]["ClockTime"];
            work_end?: components["schemas"]["ClockTime"];
            hours_per_week?: number;
            available_from?: components["schemas"]["CalendarDate"];
        };
        /** @description One candidate against one role's availability and time-zone filters. */
        AvailabilityCheck: {
            candidate_id: components["schemas"]["Id"];
            candidate_name: string;
            passed: boolean;
            /** @description Why the candidate does not pass, in words; empty when they do. */
            reasons: string[];
            /**
             * Format: double
             * @description Hours of the role's working day the candidate's working hours cover; null when the role has no time zone or the candidate no availability.
             */
            overlap_hours: number | null;
        };
        Role: {
            id: components["schemas"]["Id"];
            title: string;
            company: string | null;
            /** @description The raw job description. */
            description: string;
            /** @description The parser's structured extraction (the AI service's `RoleRequirements`). */
            requirements: components["schemas"]["JSONObject"];
            must_haves: string[];
            nice_to_haves: string[];
            /** @description Canonical taxonomy ids. */
            required_certifications: string[];
            /** @description Canonical taxonomy ids. */
            required_software: string[];
            /** @description Fewest years of experience the role accepts; `null` when the JD gives no number (a `0` sent in is stored as `null`). */
            min_years_experience: number | null;
            /** @description IANA zone the role operates in. Its working day is 09:00 to 17:00 there. */
            timezone: string | null;
            /** @description Hours of the role's working day a candidate's working hours must cover; `null` when the role does not ask. */
            min_overlap_hours: number | null;
            /** @description Hours a week the role needs; a candidate must offer at least as many. `null` when the role does not ask. */
            hours_per_week: number | null;
            starts_on: components["schemas"]["CalendarDate"] | null;
            status: components["schemas"]["RoleStatus"];
            embedding_model: string | null;
            /** Format: date-time */
            embedded_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description Body for creating or updating a role. Every field is optional on the
         *     wire so a `PUT` can send only what changes; `title` is required when
         *     creating and may not be nulled.
         */
        RoleInput: {
            title?: string;
            company?: string | null;
            /** @description `null` clears it to an empty string. */
            description?: string | null;
            requirements?: components["schemas"]["JSONObject"];
            must_haves?: string[];
            nice_to_haves?: string[];
            required_certifications?: string[];
            required_software?: string[];
            min_years_experience?: number | null;
            timezone?: string | null;
            /** @description Needs `timezone`. Supply it at intake when the JD does not state it; a `0` is stored as `null`. */
            min_overlap_hours?: number | null;
            /** @description Supply it at intake when the JD does not state it; a `0` is stored as `null`. */
            hours_per_week?: number | null;
            starts_on?: components["schemas"]["CalendarDate"] | null;
            /** @description Defaults to `open` on create. */
            status?: components["schemas"]["RoleStatus"];
        };
        Match: {
            id: components["schemas"]["Id"];
            role_id: components["schemas"]["Id"];
            candidate_id: components["schemas"]["Id"];
            /** Format: double */
            score: number;
            explanation: string;
            /** @description Per-criterion scoring detail. */
            breakdown: components["schemas"]["JSONObject"];
            status: components["schemas"]["MatchStatus"];
            /**
             * Format: date-time
             * @description Set when ops released the match to the employer.
             */
            released_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** @description Denormalised from the role so a shortlist needs one request. */
            role_title: string;
            /** @description Denormalised from the candidate. */
            candidate_name: string;
        };
        /** @description The ops-editable part of a match. Fields not sent keep their value. */
        MatchUpdate: {
            /** Format: double */
            score?: number;
            /** @description `null` clears it to an empty string. */
            explanation?: string | null;
            breakdown?: components["schemas"]["JSONObject"];
            status?: components["schemas"]["MatchStatus"];
        };
        MatchCreate: {
            role_id: components["schemas"]["Id"];
            candidate_id: components["schemas"]["Id"];
            /** Format: double */
            score: number;
            explanation?: string | null;
            breakdown?: components["schemas"]["JSONObject"];
            /** @description Defaults to `proposed`. */
            status?: components["schemas"]["MatchStatus"];
        };
        ReleaseInput: {
            /** @description Recorded on the review event. */
            reason?: string;
        };
        /**
         * @description One background job in the Postgres-backed queue (the `jobs` table). A
         *     worker claims a `queued` job whose `run_at` has passed, runs the handler
         *     for its `kind`, and marks it `succeeded`. A failing attempt puts it back
         *     to `queued` with `run_at` pushed out by a backoff until `attempts`
         *     reaches `max_attempts`, when it lands in `failed` with `last_error` set.
         */
        Job: {
            id: components["schemas"]["JobId"];
            /** @description Names the handler that runs it, e.g. `embed_role` or `parse_resume`. */
            kind: string;
            /** @description Handler-specific input, e.g. `{"role_id": "…"}`. */
            payload: components["schemas"]["JSONObject"];
            status: components["schemas"]["JobStatus"];
            /** @description Higher runs first. */
            priority: number;
            /**
             * Format: date-time
             * @description Not before this time. Retry backoff pushes it into the future.
             */
            run_at: string;
            /** @description Claims so far, including one in progress. */
            attempts: number;
            max_attempts: number;
            /** @description The most recent failed attempt's error; kept on a `failed` job, cleared on success. */
            last_error: string | null;
            /** @description Id of the worker that last claimed it. */
            worker: string | null;
            /**
             * Format: date-time
             * @description When the current or most recent attempt was claimed.
             */
            started_at: string | null;
            /**
             * Format: date-time
             * @description Set when the job reached `succeeded` or `failed`.
             */
            finished_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        JobCreate: {
            /**
             * @description Must be a kind the worker has a handler for; otherwise a 422 naming the known kinds.
             * @example embed_role
             */
            kind: string;
            payload?: components["schemas"]["JSONObject"];
            /** @description Defaults to 0. Higher runs first. */
            priority?: number;
            /**
             * Format: date-time
             * @description Delay the job until this time. Defaults to now.
             */
            run_at?: string;
            /** @description Defaults to 3. */
            max_attempts?: number;
        };
    };
    responses: {
        /** @description Malformed JSON or an unknown field. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or unknown `X-Role`. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The role may not call this operation, or a talent request is missing its candidate id. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such row, or one the caller may not see. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A unique constraint (duplicate email, duplicate role/candidate pair) or a delete blocked by history. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description One or more fields are invalid; `fields` maps each to a message. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Id: components["schemas"]["Id"];
        JobId: components["schemas"]["JobId"];
        /** @description Page size; default 50, max 200. */
        Limit: number;
        Offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Postgres and the AI service are both reachable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description At least one dependency failed; `checks` names it. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listCandidates: {
        parameters: {
            query?: {
                status?: components["schemas"]["CandidateStatus"];
                /** @description Page size; default 50, max 200. */
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    createCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The candidate. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateInput"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    deleteCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    putProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInput"];
            };
        };
        responses: {
            /** @description Replaced an existing profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Created the candidate's first profile. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    deleteProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    uploadResume: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** @description The file itself, at most 5 MB and 10 pages. */
        requestBody: {
            content: {
                "application/pdf": string;
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Text extracted and stored; the parse is queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The file is larger than 5 MB. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The file is neither a PDF nor a DOCX. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The file is empty, damaged, password-protected, has no text, or has too many pages or too much text; `error` says which. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The AI service, which reads the file, is unavailable. Nothing was stored; try again. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getResumeJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The candidate's availability. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkAvailability"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    putAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkAvailabilityInput"];
            };
        };
        responses: {
            /** @description Replaced what was stored. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkAvailability"];
                };
            };
            /** @description Stored for the first time. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkAvailability"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listRoles: {
        parameters: {
            query?: {
                status?: components["schemas"]["RoleStatus"];
                /** @description Exact match. */
                company?: string;
                /** @description Page size; default 50, max 200. */
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The role. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleInput"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listRoleAvailability: {
        parameters: {
            query?: {
                /** @description Page size; default 50, max 200. */
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active candidates by name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityCheck"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listMatches: {
        parameters: {
            query?: {
                role_id?: components["schemas"]["Id"];
                candidate_id?: components["schemas"]["Id"];
                status?: components["schemas"]["MatchStatus"];
                /** @description Page size; default 50, max 200. */
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grouped by role, best score first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    createMatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchCreate"];
            };
        };
        responses: {
            /** @description Created, unreleased. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The match. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchUpdate"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    deleteMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    releaseMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReleaseInput"];
            };
        };
        responses: {
            /** @description The match after the change. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    unreleaseMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReleaseInput"];
            };
        };
        responses: {
            /** @description The match after the change. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listJobs: {
        parameters: {
            query?: {
                status?: components["schemas"]["JobStatus"];
                kind?: string;
                /** @description Page size; default 50, max 200. */
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    createJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description An identical job was already queued; it is returned instead of a duplicate. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Queued. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
