/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness of the API and its dependencies */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List candidates */
        get: operations["listCandidates"];
        put?: never;
        /**
         * Create a candidate
         * @description Talent-created candidates are marked `source: self` unless a source is given.
         */
        post: operations["createCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * Fetch a candidate
         * @description Talent may only read their own record (`X-Actor` = id); another id is a 404.
         */
        get: operations["getCandidate"];
        /**
         * Update a candidate
         * @description Replaces the fields sent and keeps the rest. Talent may only update their own record.
         */
        put: operations["updateCandidate"];
        post?: never;
        /** Delete a candidate */
        delete: operations["deleteCandidate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Fetch a candidate's structured profile */
        get: operations["getProfile"];
        /**
         * Create or replace a candidate's profile
         * @description Replaces the whole profile. Omitted lists become empty and an omitted
         *     availability becomes `unknown`. Re-saving identical content keeps the
         *     stored embedding; a change to the text it was derived from clears it.
         */
        put: operations["putProfile"];
        post?: never;
        /** Delete a candidate's profile */
        delete: operations["deleteProfile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List roles
         * @description Talent only ever receives open roles; a `status` filter other than `open` returns an empty list for talent.
         */
        get: operations["listRoles"];
        put?: never;
        /** Create a role */
        post: operations["createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * Fetch a role
         * @description A role that is not open is a 404 for talent.
         */
        get: operations["getRole"];
        /**
         * Update a role
         * @description Replaces the fields sent and keeps the rest. Changing the description clears the stored embedding.
         */
        put: operations["updateRole"];
        post?: never;
        /** Delete a role */
        delete: operations["deleteRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List matches
         * @description Ops sees every match. Employers see released matches only. Talent sees
         *     released matches for their own candidate only (`X-Actor` = candidate id);
         *     a `candidate_id` filter naming someone else returns an empty list.
         */
        get: operations["listMatches"];
        put?: never;
        /** Propose a match between a role and a candidate */
        post: operations["createMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * Fetch a match
         * @description An unreleased match is a 404 for employers and talent, never a 403.
         */
        get: operations["getMatch"];
        /**
         * Edit a match's review fields
         * @description The (role, candidate) pair is immutable; sending `role_id` or `candidate_id` is a 422.
         */
        put: operations["updateMatch"];
        post?: never;
        /**
         * Delete a match
         * @description A match with review history cannot be deleted (409).
         */
        delete: operations["deleteMatch"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Release a match to the employer
         * @description Sets `released_at` and records a `release` review event with the `X-Actor` value. Releasing an already released match is a no-op.
         */
        post: operations["releaseMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{id}/unrelease": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Withdraw a released match
         * @description Clears `released_at` and records an `unrelease` review event. A no-op on an unreleased match.
         */
        post: operations["unreleaseMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description A UUID, as text.
         * @example 11111111-0000-0000-0000-000000000001
         */
        Id: string;
        /**
         * Format: date
         * @description A calendar day, `YYYY-MM-DD`.
         * @example 2026-10-14
         */
        CalendarDate: string;
        /** @description A free-form JSON object stored as JSONB. */
        JSONObject: {
            [key: string]: unknown;
        };
        /** @enum {string} */
        CandidateStatus: "active" | "archived";
        /** @enum {string} */
        RoleStatus: "open" | "filled" | "closed";
        /** @enum {string} */
        MatchStatus: "proposed" | "approved" | "rejected" | "swapped";
        /** @enum {string} */
        Availability: "immediate" | "two_weeks" | "one_month" | "unavailable" | "unknown";
        /** @enum {string} */
        HealthStatus: "ok" | "degraded";
        /**
         * @description The value of the `X-Role` header. Each operation's `x-roles` lists the personas that may call it.
         * @enum {string}
         */
        Persona: "talent" | "employer" | "ops";
        Error: {
            /** @example validation failed */
            error: string;
            /** @description Per-field messages on a 422. */
            fields?: {
                [key: string]: string;
            };
        };
        HealthResponse: {
            status: components["schemas"]["HealthStatus"];
            /** @description One entry per dependency (`postgres`, `ai`): `ok` or `error: <message>`. */
            checks: {
                [key: string]: string;
            };
        };
        Candidate: {
            id: components["schemas"]["Id"];
            full_name: string;
            email: string | null;
            phone: string | null;
            location: string | null;
            resume_text: string;
            /** @description Where the record came from; `self` when talent created it. */
            source: string | null;
            status: components["schemas"]["CandidateStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description Body for creating or updating a candidate. Every field is optional on
         *     the wire so a `PUT` can send only what changes; `full_name` is required
         *     when creating and may not be nulled. `null` clears an optional field.
         */
        CandidateInput: {
            full_name?: string;
            email?: string | null;
            phone?: string | null;
            location?: string | null;
            /** @description `null` clears it to an empty string. */
            resume_text?: string | null;
            source?: string | null;
            /** @description Defaults to `active` on create. */
            status?: components["schemas"]["CandidateStatus"];
        };
        /** @description One structured profile per candidate, with the hard-filter columns promoted out of the JSON. */
        Profile: {
            id: components["schemas"]["Id"];
            candidate_id: components["schemas"]["Id"];
            /** @description The parser's structured extraction (the AI service's `CandidateProfile`). */
            profile: components["schemas"]["JSONObject"];
            headline: string | null;
            years_experience: number | null;
            /** @description Canonical taxonomy ids. */
            certifications: string[];
            /** @description Canonical taxonomy ids. */
            software: string[];
            availability: components["schemas"]["Availability"];
            available_from: components["schemas"]["CalendarDate"] | null;
            /** @description IANA zone name. */
            timezone: string | null;
            embedding_model: string | null;
            /** Format: date-time */
            embedded_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Body for `PUT …/profile`. Taxonomy lists accept free text and are stored as canonical ids. */
        ProfileInput: {
            profile?: components["schemas"]["JSONObject"];
            headline?: string | null;
            years_experience?: number | null;
            certifications?: string[];
            software?: string[];
            /** @description Defaults to `unknown`. */
            availability?: components["schemas"]["Availability"];
            available_from?: components["schemas"]["CalendarDate"] | null;
            /** @description IANA zone name, e.g. `America/Chicago`. */
            timezone?: string | null;
        };
        Role: {
            id: components["schemas"]["Id"];
            title: string;
            company: string | null;
            /** @description The raw job description. */
            description: string;
            /** @description The parser's structured extraction (the AI service's `RoleRequirements`). */
            requirements: components["schemas"]["JSONObject"];
            must_haves: string[];
            nice_to_haves: string[];
            /** @description Canonical taxonomy ids. */
            required_certifications: string[];
            /** @description Canonical taxonomy ids. */
            required_software: string[];
            timezone: string | null;
            starts_on: components["schemas"]["CalendarDate"] | null;
            status: components["schemas"]["RoleStatus"];
            embedding_model: string | null;
            /** Format: date-time */
            embedded_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description Body for creating or updating a role. Every field is optional on the
         *     wire so a `PUT` can send only what changes; `title` is required when
         *     creating and may not be nulled.
         */
        RoleInput: {
            title?: string;
            company?: string | null;
            /** @description `null` clears it to an empty string. */
            description?: string | null;
            requirements?: components["schemas"]["JSONObject"];
            must_haves?: string[];
            nice_to_haves?: string[];
            required_certifications?: string[];
            required_software?: string[];
            timezone?: string | null;
            starts_on?: components["schemas"]["CalendarDate"] | null;
            /** @description Defaults to `open` on create. */
            status?: components["schemas"]["RoleStatus"];
        };
        Match: {
            id: components["schemas"]["Id"];
            role_id: components["schemas"]["Id"];
            candidate_id: components["schemas"]["Id"];
            /** Format: double */
            score: number;
            explanation: string;
            /** @description Per-criterion scoring detail. */
            breakdown: components["schemas"]["JSONObject"];
            status: components["schemas"]["MatchStatus"];
            /**
             * Format: date-time
             * @description Set when ops released the match to the employer.
             */
            released_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** @description Denormalised from the role so a shortlist needs one request. */
            role_title: string;
            /** @description Denormalised from the candidate. */
            candidate_name: string;
        };
        /** @description The ops-editable part of a match. Fields not sent keep their value. */
        MatchUpdate: {
            /** Format: double */
            score?: number;
            /** @description `null` clears it to an empty string. */
            explanation?: string | null;
            breakdown?: components["schemas"]["JSONObject"];
            status?: components["schemas"]["MatchStatus"];
        };
        MatchCreate: {
            role_id: components["schemas"]["Id"];
            candidate_id: components["schemas"]["Id"];
            /** Format: double */
            score: number;
            explanation?: string | null;
            breakdown?: components["schemas"]["JSONObject"];
            /** @description Defaults to `proposed`. */
            status?: components["schemas"]["MatchStatus"];
        };
        ReleaseInput: {
            /** @description Recorded on the review event. */
            reason?: string;
        };
    };
    responses: {
        /** @description Malformed JSON or an unknown field. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or unknown `X-Role`. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The role may not call this operation, or a talent request is missing its candidate id. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such row, or one the caller may not see. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A unique constraint (duplicate email, duplicate role/candidate pair) or a delete blocked by history. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description One or more fields are invalid; `fields` maps each to a message. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Id: components["schemas"]["Id"];
        /** @description Page size; default 50, max 200. */
        Limit: number;
        Offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Postgres and the AI service are both reachable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description At least one dependency failed; `checks` names it. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listCandidates: {
        parameters: {
            query?: {
                status?: components["schemas"]["CandidateStatus"];
                /** @description Page size; default 50, max 200. */
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    createCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The candidate. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateInput"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    deleteCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    putProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInput"];
            };
        };
        responses: {
            /** @description Replaced an existing profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Created the candidate's first profile. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    deleteProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listRoles: {
        parameters: {
            query?: {
                status?: components["schemas"]["RoleStatus"];
                /** @description Exact match. */
                company?: string;
                /** @description Page size; default 50, max 200. */
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The role. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleInput"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listMatches: {
        parameters: {
            query?: {
                role_id?: components["schemas"]["Id"];
                candidate_id?: components["schemas"]["Id"];
                status?: components["schemas"]["MatchStatus"];
                /** @description Page size; default 50, max 200. */
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grouped by role, best score first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    createMatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchCreate"];
            };
        };
        responses: {
            /** @description Created, unreleased. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The match. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchUpdate"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    deleteMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    releaseMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReleaseInput"];
            };
        };
        responses: {
            /** @description The match after the change. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    unreleaseMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReleaseInput"];
            };
        };
        responses: {
            /** @description The match after the change. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
