"""Render the committed JSON seed data into the SQL files `api seed` loads.

Pure function of the two JSON files: no network, no randomness, no clock
(dates are written as `CURRENT_DATE + n` so availability stays relative to
whenever the seed runs). tests/test_seed_data.py re-renders and compares, so
a stale .sql cannot be committed unnoticed.
"""

from __future__ import annotations

import json
import re
import zoneinfo
from pathlib import Path
from typing import Any, cast

from app.schemas import CandidateProfile, RoleRequirements

REPO = Path(__file__).resolve().parents[3]
SEED_DIR = REPO / "infra" / "db" / "seed"
DATA_DIR = SEED_DIR / "data"
CANDIDATES_JSON = DATA_DIR / "candidates.json"
ROLES_JSON = DATA_DIR / "roles.json"
CANDIDATES_SQL = SEED_DIR / "010_candidates.sql"
ROLES_SQL = SEED_DIR / "020_roles.sql"

# Dollar-quote tag for free text. Asserted absent from every value.
Q = "$seed$"


def quote(value: str | None) -> str:
    if value is None:
        return "NULL"
    if Q in value:
        raise ValueError(f"value contains the quote tag {Q!r}")
    return f"{Q}{value}{Q}"


def jsonb(value: object) -> str:
    return quote(json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))) + "::jsonb"


def text_array(values: list[str]) -> str:
    for v in values:
        if not v.replace("_", "").isalnum():
            raise ValueError(f"array value {v!r} is not a plain id")
    return "'{" + ",".join(values) + "}'"


def relative_date(days: int | None) -> str:
    return "NULL" if days is None else f"CURRENT_DATE + {int(days)}"


def clock(value: str) -> str:
    """A time of day, HH:MM, checked before it is written into SQL."""
    if not re.fullmatch(r"([01]\d|2[0-3]):[0-5]\d", value):
        raise ValueError(f"{value!r} is not a time of day as HH:MM")
    return value


def _check_timezone(name: str | None) -> None:
    if name is not None and name not in zoneinfo.available_timezones():
        raise ValueError(f"{name!r} is not an IANA timezone")


def load_json(path: Path) -> dict[str, Any]:
    return cast(dict[str, Any], json.loads(path.read_text(encoding="utf-8")))


# Only for the seed candidates who were inserted: one whose email a demo user
# already holds was skipped by ON CONFLICT, and a row for them here would
# violate the foreign key, which ON CONFLICT does not catch.
SEEDED = "WHERE EXISTS (SELECT 1 FROM candidates c WHERE c.id = v.candidate_id::uuid)"


def render_candidates(data: dict[str, Any]) -> str:
    candidates = cast(list[dict[str, Any]], data["candidates"])
    lines = [
        "-- GENERATED by `make seed-render` from infra/db/seed/data/candidates.json. Do not edit;",
        "-- edit the JSON (or regenerate it with `make seed-generate`) and re-render.",
        "--",
        f"-- {len(candidates)} synthetic finance / accounting candidates with structured profiles.",
        "-- Embeddings are left NULL; 090_embed_jobs.sql queues the jobs that fill them.",
        "-- Fixed ids plus a targetless ON CONFLICT keep this idempotent, even when a demo",
        "-- user has reused one of the seed emails: that seed candidate is skipped, and so",
        "-- are their profile and availability below, which would have no row to attach to.",
        "",
        "INSERT INTO candidates (id, full_name, email, phone, location, source, status, resume_text) VALUES",
    ]
    rows = [
        "    ("
        + ", ".join(
            [
                quote(c["id"]),
                quote(c["full_name"]),
                quote(c["email"]),
                quote(c.get("phone")),
                quote(c.get("location")),
                quote(c.get("source")),
                quote(c["status"]),
                quote(c["resume_text"]),
            ]
        )
        + ")"
        for c in candidates
    ]
    lines.append(",\n".join(rows))
    lines.append("ON CONFLICT DO NOTHING;")
    lines.append("")
    lines.append(
        "INSERT INTO candidate_profiles\n"
        "    (candidate_id, headline, years_experience, certifications, software, availability, available_from, timezone, profile)\n"
        "SELECT v.candidate_id::uuid, v.headline, v.years_experience::integer, v.certifications::text[], v.software::text[],\n"
        "       v.availability, v.available_from::date, v.timezone, v.profile\n"
        "FROM (VALUES"
    )
    rows: list[str] = []
    for c in candidates:
        profile = CandidateProfile.model_validate(c["profile"])
        _check_timezone(profile.timezone)
        days = cast(int | None, c.get("available_in_days"))
        # The JSONB keeps the whole parser-shaped profile; available_from is
        # the one field only known at seed time, so it is spliced in here and
        # matches the column exactly.
        stored = profile.model_dump(mode="json", exclude={"available_from"})
        rows.append(
            "    ("
            + ", ".join(
                [
                    quote(c["id"]),
                    quote(profile.headline),
                    "NULL" if profile.years_experience is None else str(profile.years_experience),
                    text_array(profile.certifications),
                    text_array(profile.software),
                    quote(profile.availability),
                    relative_date(days),
                    quote(profile.timezone),
                    f"{jsonb(stored)} || jsonb_build_object('available_from', ({relative_date(days)})::text)",
                ]
            )
            + ")"
        )
    lines.append(",\n".join(rows))
    lines.append(
        ") AS v (candidate_id, headline, years_experience, certifications, software, availability, available_from, timezone, profile)\n"
        + SEEDED
    )
    lines.append("ON CONFLICT DO NOTHING;")
    lines.append("")
    lines.append(
        "-- What the candidate said about when and where they can work. A resume cannot say it,\n"
        "-- so the time zone is repeated here as the candidate's own answer. Candidates with no\n"
        "-- row have not answered and are excluded from matching.\n"
        "INSERT INTO candidate_availability\n"
        "    (candidate_id, timezone, work_start, work_end, hours_per_week, available_from)\n"
        "SELECT v.candidate_id::uuid, v.timezone, v.work_start::time, v.work_end::time, v.hours_per_week::integer, v.available_from::date\n"
        "FROM (VALUES"
    )
    rows = []
    for c in candidates:
        answers = (c.get("available_in_days"), c.get("work_start"), c.get("work_end"), c.get("hours_per_week"))
        if all(a is None for a in answers):
            continue
        if any(a is None for a in answers):
            raise ValueError(f"{c['id']}: availability is all four answers or none")
        days, start, end, per_week = answers
        timezone = cast(str | None, c["profile"]["timezone"])
        if timezone is None:
            raise ValueError(f"{c['id']}: availability needs a time zone")
        _check_timezone(timezone)
        rows.append(
            "    ("
            + ", ".join(
                [
                    quote(c["id"]),
                    quote(timezone),
                    f"'{clock(cast(str, start))}'",
                    f"'{clock(cast(str, end))}'",
                    str(int(cast(int, per_week))),
                    relative_date(cast(int, days)),
                ]
            )
            + ")"
        )
    lines.append(",\n".join(rows))
    lines.append(") AS v (candidate_id, timezone, work_start, work_end, hours_per_week, available_from)\n" + SEEDED)
    lines.append("ON CONFLICT DO NOTHING;")
    return "\n".join(lines) + "\n"


def render_roles(data: dict[str, Any]) -> str:
    roles = cast(list[dict[str, Any]], data["roles"])
    lines = [
        "-- GENERATED by `make seed-render` from infra/db/seed/data/roles.json. Do not edit;",
        "-- edit the JSON and re-render.",
        "--",
        f"-- {len(roles)} sample job descriptions whose hard filters carve different slices of the",
        "-- seeded candidates. Embeddings are left NULL; 090_embed_jobs.sql queues them.",
        "",
        "INSERT INTO roles\n"
        "    (id, title, company, description, requirements, must_haves, nice_to_haves,\n"
        "     required_certifications, required_software, min_years_experience, timezone,\n"
        "     min_overlap_hours, hours_per_week, starts_on, status)\n"
        "VALUES",
    ]
    rows: list[str] = []
    for r in roles:
        req = RoleRequirements.model_validate(r["requirements"])
        _check_timezone(req.timezone)
        days = cast(int | None, r.get("starts_in_days"))
        stored = req.model_dump(mode="json", exclude={"starts_on"})
        # `requirements` stays what the JD says. Where the JD gives no number,
        # the column holds what the employer answered at intake.
        intake = cast(dict[str, int], r.get("intake", {}))
        if unknown := set(intake) - {"min_overlap_hours", "hours_per_week"}:
            raise ValueError(f"{r['id']}: intake has {sorted(unknown)}")
        overlap = req.min_overlap_hours if req.min_overlap_hours is not None else intake.get("min_overlap_hours")
        per_week = req.hours_per_week if req.hours_per_week is not None else intake.get("hours_per_week")
        if overlap is not None and req.timezone is None:
            raise ValueError(f"{r['id']}: an overlap needs the role's time zone (roles_overlap_needs_timezone)")
        rows.append(
            "    ("
            + ", ".join(
                [
                    quote(r["id"]),
                    quote(r["title"]),
                    quote(r.get("company")),
                    quote(r["description"]),
                    f"{jsonb(stored)} || jsonb_build_object('starts_on', ({relative_date(days)})::text)",
                    jsonb(req.must_haves),
                    jsonb(req.nice_to_haves),
                    text_array(req.required_certifications),
                    text_array(req.required_software),
                    "NULL" if req.min_years_experience is None else str(req.min_years_experience),
                    quote(req.timezone),
                    "NULL" if overlap is None else str(int(overlap)),
                    "NULL" if per_week is None else str(int(per_week)),
                    relative_date(days),
                    quote(r.get("status", "open")),
                ]
            )
            + ")"
        )
    lines.append(",\n".join(rows))
    lines.append("ON CONFLICT DO NOTHING;")
    return "\n".join(lines) + "\n"


def render_all() -> dict[Path, str]:
    """Every rendered file, keyed by destination."""
    return {
        CANDIDATES_SQL: render_candidates(load_json(CANDIDATES_JSON)),
        ROLES_SQL: render_roles(load_json(ROLES_JSON)),
    }


def write_all() -> list[Path]:
    written: list[Path] = []
    for path, content in render_all().items():
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written
