-- GENERATED by `make seed-render` from infra/db/seed/data/roles.json. Do not edit;
-- edit the JSON and re-render.
--
-- 12 sample job descriptions whose hard filters carve different slices of the
-- seeded candidates. Embeddings are left NULL; 090_embed_jobs.sql queues them.

INSERT INTO roles
    (id, title, company, description, requirements, must_haves, nice_to_haves,
     required_certifications, required_software, min_years_experience, timezone,
     min_overlap_hours, hours_per_week, starts_on, status)
VALUES
    ($seed$22222222-0000-0000-0000-000000000001$seed$, $seed$Senior Accountant$seed$, $seed$Northwind Foods$seed$, $seed$Northwind Foods is a $40M consumer packaged goods business (frozen and shelf-stable snacks sold through grocery and club channels) based in Chicago. We are hiring a Senior Accountant to own the month-end close.

What you will do
- Own the monthly close across three legal entities in NetSuite: journal entries, accruals, prepaids, fixed assets, intercompany eliminations and the consolidated trial balance.
- Prepare balance sheet reconciliations and drive the close from 12 business days down to 7.
- Support trade-spend and broker-commission accruals with the sales finance team.
- Prepare PBC schedules for the annual audit and respond to auditor requests.
- Document close procedures and help train a staff accountant.

What we need
- Active CPA.
- 5+ years of accounting experience with at least 2 years running a month-end close.
- Hands-on NetSuite experience (saved searches, journal imports, multi-subsidiary).
- Strong US GAAP fundamentals, including accruals and fixed-asset accounting.
- Available to work Central time hours; hybrid, 2 days a week in our Chicago office.
- Able to start within two weeks.

Nice to have
- QuickBooks experience (our acquired brand still runs on it during migration).
- CPG or food and beverage industry experience.
- Exposure to trade promotion accounting.$seed$, $seed${"hours_per_week":null,"industries":["consumer_packaged_goods","food_and_beverage"],"min_overlap_hours":null,"min_years_experience":5,"must_haves":["Active CPA","5+ years of accounting experience with at least 2 years running a month-end close","Hands-on NetSuite experience (saved searches, journal imports, multi-subsidiary)","Strong US GAAP fundamentals, including accruals and fixed-asset accounting","Available to work Central time hours; hybrid, 2 days a week in our Chicago office","Able to start within two weeks"],"nice_to_haves":["QuickBooks experience","CPG or food and beverage industry experience","Exposure to trade promotion accounting"],"other_industries":[],"other_preferred_certifications":[],"other_preferred_software":[],"other_required_certifications":[],"other_required_software":[],"preferred_certifications":[],"preferred_software":["quickbooks"],"required_certifications":["cpa_us"],"required_qualifications":[{"accept_equivalents":true,"canonical":"cpa_us","equivalents_stated":false,"name_as_written":"CPA","quote":"Active CPA"}],"required_software":["netsuite"],"timezone":"America/Chicago","title":"Senior Accountant"}$seed$::jsonb || jsonb_build_object('starts_on', (CURRENT_DATE + 7)::text), $seed$["Active CPA","5+ years of accounting experience with at least 2 years running a month-end close","Hands-on NetSuite experience (saved searches, journal imports, multi-subsidiary)","Strong US GAAP fundamentals, including accruals and fixed-asset accounting","Available to work Central time hours; hybrid, 2 days a week in our Chicago office","Able to start within two weeks"]$seed$::jsonb, $seed$["QuickBooks experience","CPG or food and beverage industry experience","Exposure to trade promotion accounting"]$seed$::jsonb, '{cpa_us}', '{netsuite}', 5, $seed$America/Chicago$seed$, 6, 40, CURRENT_DATE + 7, $seed$open$seed$),
    ($seed$22222222-0000-0000-0000-000000000002$seed$, $seed$Staff Accountant$seed$, $seed$Brightline Analytics$seed$, $seed$Brightline Analytics is a 60-person Series A SaaS company in San Francisco. This is our first in-house accounting hire; until now the books have been kept by an outsourced firm in QuickBooks Online.

Responsibilities
- Run the day-to-day books in QuickBooks Online: AP through Bill.com, expense reports, customer invoicing and cash application.
- Prepare the monthly close package: bank reconciliations, accruals, prepaid amortisation and deferred revenue schedules.
- Reconcile Stripe payouts to invoices.
- Help the outsourced firm with quarterly sales-tax filings and the year-end 1099 run.
- Take part in our planned move from QuickBooks to NetSuite next year.

Requirements
- 1-4 years of accounting experience, ideally at a startup or a small firm.
- Proficient in QuickBooks Online.
- Comfortable in Excel (lookups, pivots).
- Working knowledge of accrual accounting under US GAAP.
- Based in the Pacific time zone; remote-friendly.

Preferred
- Bill.com and Expensify experience.
- Exposure to ASC 606 or SaaS deferred revenue.
- CPA track.$seed$, $seed${"hours_per_week":null,"industries":["saas"],"min_overlap_hours":null,"min_years_experience":1,"must_haves":["1-4 years of accounting experience, ideally at a startup or a small firm","Proficient in QuickBooks Online","Comfortable in Excel (lookups, pivots)","Working knowledge of accrual accounting under US GAAP","Based in the Pacific time zone; remote-friendly"],"nice_to_haves":["Bill.com and Expensify experience","Exposure to ASC 606 or SaaS deferred revenue","CPA track"],"other_industries":[],"other_preferred_certifications":[],"other_preferred_software":[],"other_required_certifications":[],"other_required_software":[],"preferred_certifications":[],"preferred_software":["bill_com","expensify"],"required_certifications":[],"required_qualifications":[],"required_software":["quickbooks"],"timezone":"America/Los_Angeles","title":"Staff Accountant"}$seed$::jsonb || jsonb_build_object('starts_on', (CURRENT_DATE + 21)::text), $seed$["1-4 years of accounting experience, ideally at a startup or a small firm","Proficient in QuickBooks Online","Comfortable in Excel (lookups, pivots)","Working knowledge of accrual accounting under US GAAP","Based in the Pacific time zone; remote-friendly"]$seed$::jsonb, $seed$["Bill.com and Expensify experience","Exposure to ASC 606 or SaaS deferred revenue","CPA track"]$seed$::jsonb, '{}', '{quickbooks}', 1, $seed$America/Los_Angeles$seed$, 5, 40, CURRENT_DATE + 21, $seed$open$seed$),
    ($seed$22222222-0000-0000-0000-000000000003$seed$, $seed$Controller$seed$, $seed$Cascade Precision Manufacturing$seed$, $seed$Cascade Precision Manufacturing machines aerospace and medical components at two plants in Colorado and Utah ($85M revenue, 300 employees, private-equity owned). We are replacing a retiring Controller.

The role
- Lead a team of six (AP, AR, payroll, two staff accountants, a cost accountant).
- Own the monthly close and consolidated reporting for two operating entities and a holding company in Microsoft Dynamics 365 Business Central.
- Own inventory and standard-cost accounting, including annual cost roll and physical inventory.
- Run the annual audit with our Big 4 auditors and the quarterly lender reporting package.
- Maintain the internal control framework the PE sponsor expects (SOX-style, not SEC-registered).
- Partner with the CFO on the budget and on integrating acquisitions.

Must have
- CPA.
- 5+ years of progressive accounting experience, at least 3 as a Controller or Assistant Controller in a manufacturing business.
- Experience with Microsoft Dynamics 365 (Business Central or Finance).
- Standard costing and inventory valuation under US GAAP.
- Mountain time; on-site in Denver 3 days a week.

Preferred
- CMA.
- Purchase accounting / acquisition integration experience.
- Power BI for management reporting.$seed$, $seed${"hours_per_week":null,"industries":["manufacturing"],"min_overlap_hours":null,"min_years_experience":5,"must_haves":["CPA","5+ years of progressive accounting experience, at least 3 as a Controller or Assistant Controller in a manufacturing business","Experience with Microsoft Dynamics 365 (Business Central or Finance)","Standard costing and inventory valuation under US GAAP","Mountain time; on-site in Denver 3 days a week"],"nice_to_haves":["CMA","Purchase accounting / acquisition integration experience","Power BI for management reporting"],"other_industries":[],"other_preferred_certifications":[],"other_preferred_software":[],"other_required_certifications":[],"other_required_software":[],"preferred_certifications":["cma"],"preferred_software":["power_bi"],"required_certifications":["cpa_us"],"required_qualifications":[{"accept_equivalents":true,"canonical":"cpa_us","equivalents_stated":false,"name_as_written":"CPA","quote":"CPA"}],"required_software":["microsoft_dynamics_365"],"timezone":"America/Denver","title":"Controller"}$seed$::jsonb || jsonb_build_object('starts_on', (CURRENT_DATE + 45)::text), $seed$["CPA","5+ years of progressive accounting experience, at least 3 as a Controller or Assistant Controller in a manufacturing business","Experience with Microsoft Dynamics 365 (Business Central or Finance)","Standard costing and inventory valuation under US GAAP","Mountain time; on-site in Denver 3 days a week"]$seed$::jsonb, $seed$["CMA","Purchase accounting / acquisition integration experience","Power BI for management reporting"]$seed$::jsonb, '{cpa_us}', '{microsoft_dynamics_365}', 5, $seed$America/Denver$seed$, NULL, 40, CURRENT_DATE + 45, $seed$open$seed$),
    ($seed$22222222-0000-0000-0000-000000000004$seed$, $seed$FP&A Manager$seed$, $seed$Harbor & Vine$seed$, $seed$Harbor & Vine is a direct-to-consumer home goods brand ($120M revenue) headquartered in New York. We are hiring an FP&A Manager to own the operating plan.

You will
- Own the annual budget and the monthly rolling forecast in Workday Adaptive Planning.
- Build and maintain the three-statement model and the weekly cash forecast.
- Deliver the monthly variance analysis and the board reporting pack.
- Partner with marketing on CAC/LTV and with operations on inventory and freight forecasts.
- Manage one senior financial analyst.

Requirements
- 5+ years in FP&A or corporate finance, including at least 1 year managing a planning tool.
- Advanced Excel modelling.
- Experience administering Workday Adaptive Planning (or a comparable tool with a willingness to learn ours).
- Eastern time; hybrid in New York.

Preferred
- E-commerce or consumer brand experience.
- SQL or Looker for self-serve reporting.
- NetSuite as the source ledger.
- CFA or CPA.$seed$, $seed${"hours_per_week":null,"industries":["ecommerce","retail"],"min_overlap_hours":null,"min_years_experience":5,"must_haves":["5+ years in FP&A or corporate finance, including at least 1 year managing a planning tool","Advanced Excel modelling","Experience administering Workday Adaptive Planning","Eastern time; hybrid in New York"],"nice_to_haves":["E-commerce or consumer brand experience","SQL or Looker for self-serve reporting","NetSuite as the source ledger","CFA or CPA"],"other_industries":[],"other_preferred_certifications":[],"other_preferred_software":[],"other_required_certifications":[],"other_required_software":[],"preferred_certifications":["cfa","cpa_us"],"preferred_software":["sql","looker","netsuite"],"required_certifications":[],"required_qualifications":[],"required_software":["adaptive_planning","excel"],"timezone":"America/New_York","title":"FP&A Manager"}$seed$::jsonb || jsonb_build_object('starts_on', (CURRENT_DATE + 30)::text), $seed$["5+ years in FP&A or corporate finance, including at least 1 year managing a planning tool","Advanced Excel modelling","Experience administering Workday Adaptive Planning","Eastern time; hybrid in New York"]$seed$::jsonb, $seed$["E-commerce or consumer brand experience","SQL or Looker for self-serve reporting","NetSuite as the source ledger","CFA or CPA"]$seed$::jsonb, '{}', '{adaptive_planning,excel}', 5, $seed$America/New_York$seed$, 4, 40, CURRENT_DATE + 30, $seed$open$seed$),
    ($seed$22222222-0000-0000-0000-000000000005$seed$, $seed$Tax Manager$seed$, $seed$Ridgeline Advisory Group$seed$, $seed$Ridgeline Advisory Group is a 45-person CPA firm in Atlanta serving closely held businesses, real estate partnerships and their owners. We are adding a Tax Manager ahead of the 2027 filing season.

Responsibilities
- Review federal and multi-state returns for partnerships, S-corporations and C-corporations, plus the related individual returns.
- Manage a portfolio of 60-80 clients and their quarterly estimates.
- Handle IRS and state notices and represent clients in examinations.
- Prepare and review ASC 740 provisions for our handful of audited corporate clients.
- Supervise and develop two tax seniors and a seasonal associate.

Requirements
- Active US CPA license; you will sign client returns (an EA with a strong review background will be considered for a Senior title).
- 7+ years of public accounting tax experience, 2+ reviewing.
- Deep experience with partnership taxation and real estate.
- Comfortable in QuickBooks for client books cleanup.
- Eastern time zone; hybrid in Atlanta during busy season.

Preferred
- CCH Axcess or similar tax software.
- Experience with R&D credit studies.
- Master of Taxation.$seed$, $seed${"hours_per_week":null,"industries":["accounting_services","real_estate"],"min_overlap_hours":null,"min_years_experience":7,"must_haves":["Active US CPA license; you will sign client returns","7+ years of public accounting tax experience, 2+ reviewing","Deep experience with partnership taxation and real estate","Comfortable in QuickBooks for client books cleanup","Eastern time zone; hybrid in Atlanta during busy season"],"nice_to_haves":["CCH Axcess or similar tax software","Experience with R&D credit studies","Master of Taxation"],"other_industries":[],"other_preferred_certifications":[],"other_preferred_software":["CCH Axcess"],"other_required_certifications":[],"other_required_software":[],"preferred_certifications":[],"preferred_software":[],"required_certifications":["cpa_us"],"required_qualifications":[{"accept_equivalents":false,"canonical":"cpa_us","equivalents_stated":true,"name_as_written":"US CPA","quote":"Active US CPA license; you will sign client returns"}],"required_software":["quickbooks"],"timezone":"America/New_York","title":"Tax Manager"}$seed$::jsonb || jsonb_build_object('starts_on', (CURRENT_DATE + 60)::text), $seed$["Active US CPA license; you will sign client returns","7+ years of public accounting tax experience, 2+ reviewing","Deep experience with partnership taxation and real estate","Comfortable in QuickBooks for client books cleanup","Eastern time zone; hybrid in Atlanta during busy season"]$seed$::jsonb, $seed$["CCH Axcess or similar tax software","Experience with R&D credit studies","Master of Taxation"]$seed$::jsonb, '{cpa_us}', '{quickbooks}', 7, $seed$America/New_York$seed$, NULL, 40, CURRENT_DATE + 60, $seed$open$seed$),
    ($seed$22222222-0000-0000-0000-000000000006$seed$, $seed$Payroll Manager$seed$, $seed$Summit Ridge Health$seed$, $seed$Summit Ridge Health operates 14 outpatient clinics across Colorado and New Mexico with 1,100 employees, many of them hourly and some on multi-state schedules. We are hiring a Payroll Manager.

What you will own
- Bi-weekly payroll for 1,100 employees in ADP Workforce Now, including shift differentials, on-call pay and retro adjustments.
- Multi-state payroll tax registrations, filings and reconciliations.
- Payroll journal entries and accruals for the accounting team, and the monthly benefits reconciliation.
- Year-end: W-2s, ACA reporting, 401(k) audit support.
- Two payroll specialists report to you.

Requirements
- CPP (Certified Payroll Professional).
- 6+ years of payroll experience, 2+ supervising.
- ADP Workforce Now administration.
- Multi-state payroll tax expertise.
- Mountain time; on-site in Denver.

Preferred
- Healthcare or other 24/7 hourly workforce experience.
- Excel for reconciliations and audit schedules.
- SHRM-CP.$seed$, $seed${"hours_per_week":null,"industries":["healthcare"],"min_overlap_hours":null,"min_years_experience":6,"must_haves":["CPP (Certified Payroll Professional)","6+ years of payroll experience, 2+ supervising","ADP Workforce Now administration","Multi-state payroll tax expertise","Mountain time; on-site in Denver"],"nice_to_haves":["Healthcare or other 24/7 hourly workforce experience","Excel for reconciliations and audit schedules","SHRM-CP"],"other_industries":[],"other_preferred_certifications":[],"other_preferred_software":[],"other_required_certifications":[],"other_required_software":[],"preferred_certifications":["shrm_cp"],"preferred_software":["excel"],"required_certifications":["cpp"],"required_qualifications":[{"accept_equivalents":true,"canonical":"cpp","equivalents_stated":false,"name_as_written":"CPP","quote":"CPP (Certified Payroll Professional)"}],"required_software":["adp"],"timezone":"America/Denver","title":"Payroll Manager"}$seed$::jsonb || jsonb_build_object('starts_on', (CURRENT_DATE + 14)::text), $seed$["CPP (Certified Payroll Professional)","6+ years of payroll experience, 2+ supervising","ADP Workforce Now administration","Multi-state payroll tax expertise","Mountain time; on-site in Denver"]$seed$::jsonb, $seed$["Healthcare or other 24/7 hourly workforce experience","Excel for reconciliations and audit schedules","SHRM-CP"]$seed$::jsonb, '{cpp}', '{adp}', 6, $seed$America/Denver$seed$, 4, 40, CURRENT_DATE + 14, $seed$open$seed$),
    ($seed$22222222-0000-0000-0000-000000000007$seed$, $seed$Bookkeeper (part-time, remote)$seed$, $seed$Lantern House Community Foundation$seed$, $seed$Lantern House Community Foundation is a $3M nonprofit running housing and after-school programs in Houston. Our bookkeeper is leaving at the end of the month and we need someone who can start right away, about 20 hours a week, fully remote.

Responsibilities
- Keep the books in QuickBooks Online: AP through Bill.com, deposits, credit-card coding, monthly bank reconciliations.
- Track restricted vs unrestricted funds by class and prepare grant expense reports.
- Run payroll journal entries from Gusto and reconcile to the ledger.
- Prepare the monthly financial package for the executive director and the board treasurer.
- Support the annual audit and Form 990 with our outside CPA.

Requirements
- 3+ years of bookkeeping experience, nonprofit preferred.
- QuickBooks Online and Bill.com.
- Available to start immediately.
- At least 4 hours of overlap with Central time business hours.

Preferred
- Certified Public Bookkeeper or QuickBooks ProAdvisor.
- Experience with fund accounting and grant reporting.
- Gusto.$seed$, $seed${"hours_per_week":20,"industries":["nonprofit"],"min_overlap_hours":4,"min_years_experience":3,"must_haves":["3+ years of bookkeeping experience, nonprofit preferred","QuickBooks Online and Bill.com","Available to start immediately","At least 4 hours of overlap with Central time business hours"],"nice_to_haves":["Certified Public Bookkeeper or QuickBooks ProAdvisor","Experience with fund accounting and grant reporting","Gusto"],"other_industries":[],"other_preferred_certifications":[],"other_preferred_software":[],"other_required_certifications":[],"other_required_software":[],"preferred_certifications":["cpb","quickbooks_proadvisor"],"preferred_software":["gusto"],"required_certifications":[],"required_qualifications":[],"required_software":["quickbooks","bill_com"],"timezone":"America/Chicago","title":"Bookkeeper (part-time, remote)"}$seed$::jsonb || jsonb_build_object('starts_on', (CURRENT_DATE + 3)::text), $seed$["3+ years of bookkeeping experience, nonprofit preferred","QuickBooks Online and Bill.com","Available to start immediately","At least 4 hours of overlap with Central time business hours"]$seed$::jsonb, $seed$["Certified Public Bookkeeper or QuickBooks ProAdvisor","Experience with fund accounting and grant reporting","Gusto"]$seed$::jsonb, '{}', '{quickbooks,bill_com}', 3, $seed$America/Chicago$seed$, 4, 20, CURRENT_DATE + 3, $seed$open$seed$),
    ($seed$22222222-0000-0000-0000-000000000008$seed$, $seed$Revenue Accountant$seed$, $seed$Tessellate Software$seed$, $seed$Tessellate Software sells workflow software to mid-market logistics companies ($45M ARR, Series C, Austin). We are hiring a Revenue Accountant as we prepare for our first Big 4 audit.

You will
- Own revenue recognition under ASC 606 for subscription, implementation and usage-based contracts: contract review, SSP allocation, modifications.
- Maintain the deferred revenue and unbilled schedules in NetSuite (Advanced Revenue Management) and reconcile them to Salesforce bookings.
- Own commission capitalisation and amortisation under ASC 340-40.
- Build the revenue section of the audit PBC list and write technical memos for non-standard deals.
- Report ARR, bookings and churn to FP&A monthly.

Requirements
- 4+ years of accounting experience, 2+ in revenue recognition at a SaaS company.
- NetSuite (ARM preferred).
- Salesforce as the CRM system of record.
- Working knowledge of ASC 606 and ASC 340-40.
- Central time hours; remote within the US.

Preferred
- CPA.
- Stripe billing.
- Experience preparing for a first audit.$seed$, $seed${"hours_per_week":null,"industries":["saas"],"min_overlap_hours":null,"min_years_experience":4,"must_haves":["4+ years of accounting experience, 2+ in revenue recognition at a SaaS company","NetSuite (ARM preferred)","Salesforce as the CRM system of record","Working knowledge of ASC 606 and ASC 340-40","Central time hours; remote within the US"],"nice_to_haves":["CPA","Stripe billing","Experience preparing for a first audit"],"other_industries":[],"other_preferred_certifications":[],"other_preferred_software":[],"other_required_certifications":[],"other_required_software":[],"preferred_certifications":["cpa_us"],"preferred_software":["stripe"],"required_certifications":[],"required_qualifications":[],"required_software":["netsuite","salesforce"],"timezone":"America/Chicago","title":"Revenue Accountant"}$seed$::jsonb || jsonb_build_object('starts_on', (CURRENT_DATE + 30)::text), $seed$["4+ years of accounting experience, 2+ in revenue recognition at a SaaS company","NetSuite (ARM preferred)","Salesforce as the CRM system of record","Working knowledge of ASC 606 and ASC 340-40","Central time hours; remote within the US"]$seed$::jsonb, $seed$["CPA","Stripe billing","Experience preparing for a first audit"]$seed$::jsonb, '{}', '{netsuite,salesforce}', 4, $seed$America/Chicago$seed$, 6, 40, CURRENT_DATE + 30, $seed$open$seed$),
    ($seed$22222222-0000-0000-0000-000000000009$seed$, $seed$Financial Accountant (IFRS)$seed$, $seed$Kestrel Payments Ltd$seed$, $seed$Kestrel Payments is a London fintech (FCA-regulated payments institution, 180 staff) with a US parent. We are hiring a Financial Accountant to own the UK statutory and group reporting.

Responsibilities
- Prepare monthly management accounts for the UK entity in Xero and the group reporting pack for the US parent (US GAAP conversion adjustments).
- Prepare the annual statutory accounts under IFRS / FRS 102 and manage the audit.
- Quarterly VAT returns and the FCA safeguarding reconciliations.
- Balance sheet reconciliations, intercompany recharges and transfer pricing entries.
- Support the migration from Xero to NetSuite next year.

Requirements
- ACCA qualified (or ACA / CA).
- 4+ years post-qualification experience with statutory accounts.
- Xero.
- IFRS and UK GAAP; exposure to US GAAP group reporting.
- Based in the UK or Ireland; hybrid in London.

Preferred
- Fintech or regulated-entity experience.
- NetSuite.
- Power BI.$seed$, $seed${"hours_per_week":null,"industries":["fintech"],"min_overlap_hours":null,"min_years_experience":4,"must_haves":["ACCA qualified (or ACA / CA)","4+ years post-qualification experience with statutory accounts","Xero","IFRS and UK GAAP; exposure to US GAAP group reporting","Based in the UK or Ireland; hybrid in London"],"nice_to_haves":["Fintech or regulated-entity experience","NetSuite","Power BI"],"other_industries":[],"other_preferred_certifications":[],"other_preferred_software":[],"other_required_certifications":[],"other_required_software":[],"preferred_certifications":[],"preferred_software":["netsuite","power_bi"],"required_certifications":["acca"],"required_qualifications":[{"accept_equivalents":true,"canonical":"acca","equivalents_stated":true,"name_as_written":"ACCA","quote":"ACCA qualified (or ACA / CA)"}],"required_software":["xero"],"timezone":"Europe/London","title":"Financial Accountant (IFRS)"}$seed$::jsonb || jsonb_build_object('starts_on', (CURRENT_DATE + 30)::text), $seed$["ACCA qualified (or ACA / CA)","4+ years post-qualification experience with statutory accounts","Xero","IFRS and UK GAAP; exposure to US GAAP group reporting","Based in the UK or Ireland; hybrid in London"]$seed$::jsonb, $seed$["Fintech or regulated-entity experience","NetSuite","Power BI"]$seed$::jsonb, '{acca}', '{xero}', 4, $seed$Europe/London$seed$, 3, 35, CURRENT_DATE + 30, $seed$open$seed$),
    ($seed$22222222-0000-0000-0000-000000000010$seed$, $seed$Accounts Payable Specialist$seed$, $seed$Pinecrest Logistics$seed$, $seed$Pinecrest Logistics is a third-party logistics provider with 12 warehouses in the Midwest ($300M revenue). Our shared-services AP team in Chicago is adding a specialist.

What you will do
- Process 2,500+ vendor invoices a month in SAP with three-way match against purchase orders and goods receipts.
- Manage the expense-report queue in SAP Concur and enforce policy.
- Resolve vendor statement discrepancies and own the weekly payment run.
- Support month-end AP accruals and the AP ageing review.

Requirements
- 2+ years of high-volume accounts payable experience.
- SAP (any module with AP transactions).
- Central time; on-site in Chicago, start within three weeks.

Preferred
- SAP Concur.
- Logistics, distribution or manufacturing background.
- Excel for reconciliations.
- Experience with an OCR / invoice automation tool.$seed$, $seed${"hours_per_week":null,"industries":["logistics"],"min_overlap_hours":null,"min_years_experience":2,"must_haves":["2+ years of high-volume accounts payable experience","SAP (any module with AP transactions)","Central time; on-site in Chicago, start within three weeks"],"nice_to_haves":["SAP Concur","Logistics, distribution or manufacturing background","Excel for reconciliations","Experience with an OCR / invoice automation tool"],"other_industries":[],"other_preferred_certifications":[],"other_preferred_software":[],"other_required_certifications":[],"other_required_software":[],"preferred_certifications":[],"preferred_software":["concur","excel"],"required_certifications":[],"required_qualifications":[],"required_software":["sap"],"timezone":"America/Chicago","title":"Accounts Payable Specialist"}$seed$::jsonb || jsonb_build_object('starts_on', (CURRENT_DATE + 21)::text), $seed$["2+ years of high-volume accounts payable experience","SAP (any module with AP transactions)","Central time; on-site in Chicago, start within three weeks"]$seed$::jsonb, $seed$["SAP Concur","Logistics, distribution or manufacturing background","Excel for reconciliations","Experience with an OCR / invoice automation tool"]$seed$::jsonb, '{}', '{sap}', 2, $seed$America/Chicago$seed$, 4, 40, CURRENT_DATE + 21, $seed$open$seed$),
    ($seed$22222222-0000-0000-0000-000000000011$seed$, $seed$Internal Auditor$seed$, $seed$Granite Peak Bank$seed$, $seed$Granite Peak Bank is a $6B community bank holding company in Minneapolis. Internal Audit is a team of nine reporting to the Audit Committee; we are adding an auditor with a financial-reporting focus.

Responsibilities
- Plan and execute financial, operational and SOX 404 audits across lending, deposits and finance.
- Test internal controls over financial reporting and coordinate with the external auditors on reliance.
- Write clear findings and follow remediation through to closure.
- Use data analytics (Alteryx, Power BI) to build full-population tests.

Requirements
- CIA, or CPA with 3+ years in internal audit.
- 3+ years of internal or external audit experience, banking preferred.
- Working knowledge of SOX 404 and COSO.
- Central time; hybrid in Minneapolis.

Preferred
- CISA or CFE.
- Alteryx or SQL.
- Experience auditing an Oracle or SAP general ledger.$seed$, $seed${"hours_per_week":null,"industries":["banking"],"min_overlap_hours":null,"min_years_experience":3,"must_haves":["CIA, or CPA with 3+ years in internal audit","3+ years of internal or external audit experience, banking preferred","Working knowledge of SOX 404 and COSO","Central time; hybrid in Minneapolis"],"nice_to_haves":["CISA or CFE","Alteryx or SQL","Experience auditing an Oracle or SAP general ledger"],"other_industries":[],"other_preferred_certifications":[],"other_preferred_software":[],"other_required_certifications":[],"other_required_software":[],"preferred_certifications":["cisa","cfe"],"preferred_software":["alteryx","sql"],"required_certifications":["cia"],"required_qualifications":[{"accept_equivalents":true,"canonical":"cia","equivalents_stated":false,"name_as_written":"CIA","quote":"CIA, or CPA with 3+ years in internal audit"}],"required_software":[],"timezone":"America/Chicago","title":"Internal Auditor"}$seed$::jsonb || jsonb_build_object('starts_on', (CURRENT_DATE + 45)::text), $seed$["CIA, or CPA with 3+ years in internal audit","3+ years of internal or external audit experience, banking preferred","Working knowledge of SOX 404 and COSO","Central time; hybrid in Minneapolis"]$seed$::jsonb, $seed$["CISA or CFE","Alteryx or SQL","Experience auditing an Oracle or SAP general ledger"]$seed$::jsonb, '{cia}', '{}', 3, $seed$America/Chicago$seed$, NULL, 40, CURRENT_DATE + 45, $seed$open$seed$),
    ($seed$22222222-0000-0000-0000-000000000012$seed$, $seed$Fractional CFO$seed$, $seed$Juniper Robotics$seed$, $seed$Juniper Robotics builds warehouse picking robots (Series B, $18M ARR, 90 employees, Seattle). We are looking for a fractional CFO for roughly two days a week ahead of a Series C next year.

Scope
- Own the financial model, the board deck and investor reporting.
- Lead diligence readiness: clean up the NetSuite ledger, first-year audit, GAAP conversion of legacy cash-basis periods.
- Manage the cap table in Carta, option grants and 409A timing.
- Stand up FP&A discipline: annual plan, monthly variance review, headcount planning.
- Oversee the controller and the outsourced tax provider.

Requirements
- CPA.
- 15+ years of finance experience with at least one venture-backed company through a priced round.
- NetSuite.
- Comfortable with cap-table and equity accounting.
- Pacific time; on-site in Seattle one day a week.

Preferred
- Carta administration.
- Hardware or robotics experience (inventory, capitalised R&D).
- Prior fractional or interim work.$seed$, $seed${"hours_per_week":null,"industries":["technology"],"min_overlap_hours":null,"min_years_experience":15,"must_haves":["CPA","15+ years of finance experience with at least one venture-backed company through a priced round","NetSuite","Comfortable with cap-table and equity accounting","Pacific time; on-site in Seattle one day a week"],"nice_to_haves":["Carta administration","Hardware or robotics experience (inventory, capitalised R&D)","Prior fractional or interim work"],"other_industries":[],"other_preferred_certifications":[],"other_preferred_software":[],"other_required_certifications":[],"other_required_software":[],"preferred_certifications":[],"preferred_software":["carta"],"required_certifications":["cpa_us"],"required_qualifications":[{"accept_equivalents":true,"canonical":"cpa_us","equivalents_stated":false,"name_as_written":"CPA","quote":"CPA"}],"required_software":["netsuite"],"timezone":"America/Los_Angeles","title":"Fractional CFO"}$seed$::jsonb || jsonb_build_object('starts_on', (CURRENT_DATE + 14)::text), $seed$["CPA","15+ years of finance experience with at least one venture-backed company through a priced round","NetSuite","Comfortable with cap-table and equity accounting","Pacific time; on-site in Seattle one day a week"]$seed$::jsonb, $seed$["Carta administration","Hardware or robotics experience (inventory, capitalised R&D)","Prior fractional or interim work"]$seed$::jsonb, '{cpa_us}', '{netsuite}', 15, $seed$America/Los_Angeles$seed$, 3, 15, CURRENT_DATE + 14, $seed$open$seed$)
ON CONFLICT DO NOTHING;
