// Package aiclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package aiclient

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CandidateProfileAvailability.
const (
	CandidateProfileAvailabilityImmediate   CandidateProfileAvailability = "immediate"
	CandidateProfileAvailabilityOneMonth    CandidateProfileAvailability = "one_month"
	CandidateProfileAvailabilityTwoWeeks    CandidateProfileAvailability = "two_weeks"
	CandidateProfileAvailabilityUnavailable CandidateProfileAvailability = "unavailable"
	CandidateProfileAvailabilityUnknown     CandidateProfileAvailability = "unknown"
)

// Valid indicates whether the value is a known member of the CandidateProfileAvailability enum.
func (e CandidateProfileAvailability) Valid() bool {
	switch e {
	case CandidateProfileAvailabilityImmediate:
		return true
	case CandidateProfileAvailabilityOneMonth:
		return true
	case CandidateProfileAvailabilityTwoWeeks:
		return true
	case CandidateProfileAvailabilityUnavailable:
		return true
	case CandidateProfileAvailabilityUnknown:
		return true
	default:
		return false
	}
}

// Defines values for QualificationStatus.
const (
	QualificationStatusInProgress    QualificationStatus = "in_progress"
	QualificationStatusPartQualified QualificationStatus = "part_qualified"
	QualificationStatusQualified     QualificationStatus = "qualified"
)

// Valid indicates whether the value is a known member of the QualificationStatus enum.
func (e QualificationStatus) Valid() bool {
	switch e {
	case QualificationStatusInProgress:
		return true
	case QualificationStatusPartQualified:
		return true
	case QualificationStatusQualified:
		return true
	default:
		return false
	}
}

// CandidateProfile What the resume parser extracts. Maps onto candidate_profiles.
type CandidateProfile struct {
	Availability  *CandidateProfileAvailability `json:"availability,omitempty"`
	AvailableFrom *openapi_types.Date           `json:"available_from,omitempty"`

	// Certifications Certifications the candidate holds, as taxonomy ids.
	Certifications []string `json:"certifications,omitempty"`

	// GaapExposure Accounting frameworks and standards the resume names, e.g. 'US GAAP', 'ASC 606', 'IFRS 17'.
	GaapExposure []string `json:"gaap_exposure,omitempty"`

	// Headline One-line summary of the candidate, e.g. 'Senior Accountant'.
	Headline *string `json:"headline,omitempty"`

	// Industries Industries the candidate has worked in, as taxonomy ids.
	Industries []string `json:"industries,omitempty"`

	// Languages Spoken languages as ISO 639-1 codes.
	Languages []string `json:"languages,omitempty"`

	// OtherCertifications Certifications not in the taxonomy, verbatim.
	OtherCertifications []string `json:"other_certifications,omitempty"`

	// OtherIndustries Industries not in the taxonomy, verbatim.
	OtherIndustries []string `json:"other_industries,omitempty"`

	// OtherSoftware Software not in the taxonomy, verbatim.
	OtherSoftware []string `json:"other_software,omitempty"`

	// Positions Jobs held, in the order the resume lists them.
	Positions []Position `json:"positions,omitempty"`

	// Qualifications Every professional qualification the resume mentions, held or not, as written.
	Qualifications []Qualification `json:"qualifications,omitempty"`

	// Skills Free-text skills, e.g. 'month-end close'.
	Skills []string `json:"skills,omitempty"`

	// Software Software the candidate has used, as taxonomy ids.
	Software []string `json:"software,omitempty"`

	// Timezone IANA name, e.g. America/Chicago.
	Timezone        *string `json:"timezone,omitempty"`
	YearsExperience *int    `json:"years_experience,omitempty"`
}

// CandidateProfileAvailability defines model for CandidateProfile.Availability.
type CandidateProfileAvailability string

// Contact Header details the resume parser returns alongside the profile.
//
// Every field is nullable: a resume with no email gets null, not a made-up
// address, and a blank string from the model means the same thing.
type Contact struct {
	Email    *string `json:"email,omitempty"`
	FullName *string `json:"full_name,omitempty"`
	Location *string `json:"location,omitempty"`
	Phone    *string `json:"phone,omitempty"`
}

// EmbedBatchRequest defines model for EmbedBatchRequest.
type EmbedBatchRequest struct {
	Inputs []EmbedInput `json:"inputs"`
}

// EmbedBatchResponse defines model for EmbedBatchResponse.
type EmbedBatchResponse struct {
	Dim int `json:"dim"`

	// Embeddings One vector per input, in the order given.
	Embeddings [][]float32 `json:"embeddings"`
	Provider   string      `json:"provider"`

	// Texts The text each vector was computed from, in the same order.
	Texts []string `json:"texts"`
}

// EmbedInput One thing to embed: exactly one of the three fields. A profile or a
// role's requirements is rendered to its canonical text (app/embedtext.py)
// first, so the two are embedded in a comparable form.
type EmbedInput struct {
	// Profile Embedded as its canonical profile text.
	Profile *CandidateProfile `json:"profile,omitempty"`

	// Requirements Embedded as its canonical role text.
	Requirements *RoleRequirements `json:"requirements,omitempty"`

	// Text Embedded as given.
	Text *string `json:"text,omitempty"`
}

// EmbedRequest defines model for EmbedRequest.
type EmbedRequest struct {
	Text string `json:"text"`
}

// EmbedResponse defines model for EmbedResponse.
type EmbedResponse struct {
	Dim       int       `json:"dim"`
	Embedding []float32 `json:"embedding"`
	Provider  string    `json:"provider"`
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail []ValidationError `json:"detail,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	EmbeddingProvider string `json:"embedding_provider"`
	LlmProvider       string `json:"llm_provider"`
	Status            string `json:"status"`
}

// ParseJDRequest defines model for ParseJDRequest.
type ParseJDRequest struct {
	// Text The job description as plain text.
	Text string `json:"text"`
}

// ParseJDResponse defines model for ParseJDResponse.
type ParseJDResponse struct {
	Company  *string `json:"company"`
	Provider string  `json:"provider"`

	// Requirements What the JD parser extracts. Maps onto roles.
	//
	// Requirements come in two tiers that mirror the candidate profile. The
	// must-haves (`required_*`, `min_years_experience`, `starts_on`, `timezone`)
	// are the hard filters, see HARD_FILTER_COLUMNS. The nice-to-haves
	// (`preferred_*`) never exclude anyone: holding any one of them counts in a
	// candidate's favour, so "CPP or FPC" is simply both ids.
	Requirements RoleRequirements `json:"requirements"`
}

// ParseResumeRequest defines model for ParseResumeRequest.
type ParseResumeRequest struct {
	// AsOf The date years_experience is counted to. Default: today.
	AsOf *openapi_types.Date `json:"as_of,omitempty"`

	// Text The resume as plain text.
	Text string `json:"text"`
}

// ParseResumeResponse defines model for ParseResumeResponse.
type ParseResumeResponse struct {
	// Contact Header details the resume parser returns alongside the profile.
	//
	// Every field is nullable: a resume with no email gets null, not a made-up
	// address, and a blank string from the model means the same thing.
	Contact Contact `json:"contact"`

	// Profile What the resume parser extracts. Maps onto candidate_profiles.
	Profile  CandidateProfile `json:"profile"`
	Provider string           `json:"provider"`
}

// Position One job in the candidate's work history, as the resume lists it.
type Position struct {
	// Current True when the resume says the role runs to the present.
	Current *bool `json:"current,omitempty"`

	// Employer Employer as written; null if the resume names none.
	Employer *string `json:"employer,omitempty"`

	// EndYear Four-digit year the role ended; null for a current role.
	EndYear *int `json:"end_year,omitempty"`

	// StartYear Four-digit year the role began.
	StartYear *int `json:"start_year,omitempty"`

	// Title Job title as written, e.g. 'Senior Accountant'.
	Title string `json:"title"`
}

// Qualification One professional qualification exactly as the resume gives it.
//
// `canonical` is the qualification the candidate holds, never the one a
// role might want instead: an ACA is `aca_icaew`, not `cpa`.
type Qualification struct {
	// Canonical Taxonomy id of this qualification itself, e.g. 'aca_icaew'; null if it is not in the taxonomy.
	Canonical *string `json:"canonical,omitempty"`

	// IssuingBody e.g. 'ICAEW', 'ACCA', 'CPA Ontario'; null if unstated.
	IssuingBody *string `json:"issuing_body,omitempty"`

	// Jurisdiction Where it was awarded, e.g. 'UK', 'US', 'Australia'; null if it cannot be determined.
	Jurisdiction *string `json:"jurisdiction,omitempty"`

	// NameAsWritten Exactly what the resume says, e.g. 'ACA', 'CPA, CA'.
	NameAsWritten string `json:"name_as_written"`

	// Quote The resume's own words that show it, verbatim.
	Quote *string `json:"quote,omitempty"`

	// Status qualified only when fully held; 'ACCA finalist' is part_qualified, 'studying for' in_progress.
	Status       *QualificationStatus `json:"status,omitempty"`
	YearObtained *int                 `json:"year_obtained,omitempty"`
}

// QualificationStatus qualified only when fully held; 'ACCA finalist' is part_qualified, 'studying for' in_progress.
type QualificationStatus string

// RequiredQualification One qualification a role requires, and whether an equivalent will do.
type RequiredQualification struct {
	// AcceptEquivalents False only when the JD rules equivalents out, e.g. 'active US CPA licence required'.
	AcceptEquivalents *bool `json:"accept_equivalents,omitempty"`

	// Canonical Taxonomy id of the qualification asked for; null if not in the taxonomy.
	Canonical *string `json:"canonical,omitempty"`

	// EquivalentsStated True when the JD says either way ('CPA or equivalent', 'US licence required'); false means accept_equivalents is the default and the employer should confirm it at intake.
	EquivalentsStated *bool `json:"equivalents_stated,omitempty"`

	// NameAsWritten The qualification as the JD names it, e.g. 'CPA'.
	NameAsWritten string `json:"name_as_written"`

	// Quote The JD's own words, verbatim.
	Quote *string `json:"quote,omitempty"`
}

// RerankCandidate defines model for RerankCandidate.
type RerankCandidate struct {
	// ID Opaque id echoed back in the result.
	ID string `json:"id"`

	// Text Resume text or a rendered profile; whatever the model should judge.
	Text string `json:"text"`
}

// RerankRequest defines model for RerankRequest.
type RerankRequest struct {
	Candidates []RerankCandidate `json:"candidates"`

	// Role The job description, or a rendering of the role.
	Role string `json:"role"`
}

// RerankResponse defines model for RerankResponse.
type RerankResponse struct {
	Provider string `json:"provider"`

	// Results Every candidate, best first.
	Results []RerankResult `json:"results"`
}

// RerankResult defines model for RerankResult.
type RerankResult struct {
	ID      string   `json:"id"`
	Reasons []string `json:"reasons,omitempty"`
	Score   float32  `json:"score"`
}

// RoleRequirements What the JD parser extracts. Maps onto roles.
//
// Requirements come in two tiers that mirror the candidate profile. The
// must-haves (`required_*`, `min_years_experience`, `starts_on`, `timezone`)
// are the hard filters, see HARD_FILTER_COLUMNS. The nice-to-haves
// (`preferred_*`) never exclude anyone: holding any one of them counts in a
// candidate's favour, so "CPP or FPC" is simply both ids.
type RoleRequirements struct {
	// Industries Industry context of the role, as taxonomy ids.
	Industries []string `json:"industries,omitempty"`

	// MinYearsExperience Fewest total years of professional experience the JD accepts; null if it gives no number.
	MinYearsExperience *int `json:"min_years_experience,omitempty"`

	// MustHaves Every hard requirement in the JD's own words.
	MustHaves []string `json:"must_haves,omitempty"`

	// NiceToHaves Preferred but not required, in the JD's own words.
	NiceToHaves []string `json:"nice_to_haves,omitempty"`

	// OtherIndustries Industries not in the taxonomy, verbatim.
	OtherIndustries []string `json:"other_industries,omitempty"`

	// OtherPreferredCertifications Preferred certifications not in the taxonomy, verbatim.
	OtherPreferredCertifications []string `json:"other_preferred_certifications,omitempty"`

	// OtherPreferredSoftware Preferred software not in the taxonomy, verbatim.
	OtherPreferredSoftware []string `json:"other_preferred_software,omitempty"`

	// OtherRequiredCertifications Required certifications not in the taxonomy, verbatim.
	OtherRequiredCertifications []string `json:"other_required_certifications,omitempty"`

	// OtherRequiredSoftware Required software not in the taxonomy, verbatim.
	OtherRequiredSoftware []string `json:"other_required_software,omitempty"`

	// PreferredCertifications Certifications the JD lists as preferred but not required, as taxonomy ids.
	PreferredCertifications []string `json:"preferred_certifications,omitempty"`

	// PreferredSoftware Software the JD lists as preferred but not required, as taxonomy ids.
	PreferredSoftware []string `json:"preferred_software,omitempty"`

	// RequiredCertifications Certifications the role requires, as taxonomy ids.
	RequiredCertifications []string `json:"required_certifications,omitempty"`

	// RequiredQualifications Each required qualification with whether an equivalent is acceptable.
	RequiredQualifications []RequiredQualification `json:"required_qualifications,omitempty"`

	// RequiredSoftware Software the role requires, as taxonomy ids.
	RequiredSoftware []string            `json:"required_software,omitempty"`
	StartsOn         *openapi_types.Date `json:"starts_on,omitempty"`

	// Timezone IANA name the role operates in.
	Timezone *string `json:"timezone,omitempty"`
	Title    *string `json:"title,omitempty"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Ctx   *map[string]interface{}    `json:"ctx,omitempty"`
	Input interface{}                `json:"input,omitempty"`
	Loc   []ValidationError_Loc_Item `json:"loc"`
	Msg   string                     `json:"msg"`
	Type  string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for .
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for .
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// EmbedJSONRequestBody defines body for Embed for application/json ContentType.
type EmbedJSONRequestBody = EmbedRequest

// EmbedBatchJSONRequestBody defines body for EmbedBatch for application/json ContentType.
type EmbedBatchJSONRequestBody = EmbedBatchRequest

// ParseJdJSONRequestBody defines body for ParseJd for application/json ContentType.
type ParseJdJSONRequestBody = ParseJDRequest

// ParseResumeJSONRequestBody defines body for ParseResume for application/json ContentType.
type ParseResumeJSONRequestBody = ParseResumeRequest

// RerankJSONRequestBody defines body for Rerank for application/json ContentType.
type RerankJSONRequestBody = RerankRequest

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
