// Package aiclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package aiclient

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CandidateProfileAvailability.
const (
	CandidateProfileAvailabilityImmediate   CandidateProfileAvailability = "immediate"
	CandidateProfileAvailabilityOneMonth    CandidateProfileAvailability = "one_month"
	CandidateProfileAvailabilityTwoWeeks    CandidateProfileAvailability = "two_weeks"
	CandidateProfileAvailabilityUnavailable CandidateProfileAvailability = "unavailable"
	CandidateProfileAvailabilityUnknown     CandidateProfileAvailability = "unknown"
)

// Valid indicates whether the value is a known member of the CandidateProfileAvailability enum.
func (e CandidateProfileAvailability) Valid() bool {
	switch e {
	case CandidateProfileAvailabilityImmediate:
		return true
	case CandidateProfileAvailabilityOneMonth:
		return true
	case CandidateProfileAvailabilityTwoWeeks:
		return true
	case CandidateProfileAvailabilityUnavailable:
		return true
	case CandidateProfileAvailabilityUnknown:
		return true
	default:
		return false
	}
}

// CandidateProfile What the resume parser extracts. Maps onto candidate_profiles.
type CandidateProfile struct {
	Availability  *CandidateProfileAvailability `json:"availability,omitempty"`
	AvailableFrom *openapi_types.Date           `json:"available_from,omitempty"`

	// Certifications Certifications the candidate holds, as taxonomy ids.
	Certifications []string `json:"certifications,omitempty"`

	// GaapExposure Accounting frameworks and standards the resume names, e.g. 'US GAAP', 'ASC 606', 'IFRS 17'.
	GaapExposure []string `json:"gaap_exposure,omitempty"`

	// Headline One-line summary of the candidate, e.g. 'Senior Accountant'.
	Headline *string `json:"headline,omitempty"`

	// Industries Industries the candidate has worked in, as taxonomy ids.
	Industries []string `json:"industries,omitempty"`

	// Languages Spoken languages as ISO 639-1 codes.
	Languages []string `json:"languages,omitempty"`

	// OtherCertifications Certifications not in the taxonomy, verbatim.
	OtherCertifications []string `json:"other_certifications,omitempty"`

	// OtherIndustries Industries not in the taxonomy, verbatim.
	OtherIndustries []string `json:"other_industries,omitempty"`

	// OtherSoftware Software not in the taxonomy, verbatim.
	OtherSoftware []string `json:"other_software,omitempty"`

	// Positions Jobs held, in the order the resume lists them.
	Positions []Position `json:"positions,omitempty"`

	// Skills Free-text skills, e.g. 'month-end close'.
	Skills []string `json:"skills,omitempty"`

	// Software Software the candidate has used, as taxonomy ids.
	Software []string `json:"software,omitempty"`

	// Timezone IANA name, e.g. America/Chicago.
	Timezone        *string `json:"timezone,omitempty"`
	YearsExperience *int    `json:"years_experience,omitempty"`
}

// CandidateProfileAvailability defines model for CandidateProfile.Availability.
type CandidateProfileAvailability string

// Contact Header details the resume parser returns alongside the profile.
//
// Every field is nullable: a resume with no email gets null, not a made-up
// address, and a blank string from the model means the same thing.
type Contact struct {
	Email    *string `json:"email,omitempty"`
	FullName *string `json:"full_name,omitempty"`
	Location *string `json:"location,omitempty"`
	Phone    *string `json:"phone,omitempty"`
}

// EmbedRequest defines model for EmbedRequest.
type EmbedRequest struct {
	Text string `json:"text"`
}

// EmbedResponse defines model for EmbedResponse.
type EmbedResponse struct {
	Dim       int       `json:"dim"`
	Embedding []float32 `json:"embedding"`
	Provider  string    `json:"provider"`
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail []ValidationError `json:"detail,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	EmbeddingProvider string `json:"embedding_provider"`
	LlmProvider       string `json:"llm_provider"`
	Status            string `json:"status"`
}

// ParseJDRequest defines model for ParseJDRequest.
type ParseJDRequest struct {
	// Text The job description as plain text.
	Text string `json:"text"`
}

// ParseJDResponse defines model for ParseJDResponse.
type ParseJDResponse struct {
	Company  *string `json:"company"`
	Provider string  `json:"provider"`

	// Requirements What the JD parser extracts. Maps onto roles.
	Requirements RoleRequirements `json:"requirements"`
}

// ParseResumeRequest defines model for ParseResumeRequest.
type ParseResumeRequest struct {
	// AsOf The date years_experience is counted to. Default: today.
	AsOf *openapi_types.Date `json:"as_of,omitempty"`

	// Text The resume as plain text.
	Text string `json:"text"`
}

// ParseResumeResponse defines model for ParseResumeResponse.
type ParseResumeResponse struct {
	// Contact Header details the resume parser returns alongside the profile.
	//
	// Every field is nullable: a resume with no email gets null, not a made-up
	// address, and a blank string from the model means the same thing.
	Contact Contact `json:"contact"`

	// Profile What the resume parser extracts. Maps onto candidate_profiles.
	Profile  CandidateProfile `json:"profile"`
	Provider string           `json:"provider"`
}

// Position One job in the candidate's work history, as the resume lists it.
type Position struct {
	// Current True when the resume says the role runs to the present.
	Current *bool `json:"current,omitempty"`

	// Employer Employer as written; null if the resume names none.
	Employer *string `json:"employer,omitempty"`

	// EndYear Four-digit year the role ended; null for a current role.
	EndYear *int `json:"end_year,omitempty"`

	// StartYear Four-digit year the role began.
	StartYear *int `json:"start_year,omitempty"`

	// Title Job title as written, e.g. 'Senior Accountant'.
	Title string `json:"title"`
}

// RerankCandidate defines model for RerankCandidate.
type RerankCandidate struct {
	// ID Opaque id echoed back in the result.
	ID string `json:"id"`

	// Text Resume text or a rendered profile; whatever the model should judge.
	Text string `json:"text"`
}

// RerankRequest defines model for RerankRequest.
type RerankRequest struct {
	Candidates []RerankCandidate `json:"candidates"`

	// Role The job description, or a rendering of the role.
	Role string `json:"role"`
}

// RerankResponse defines model for RerankResponse.
type RerankResponse struct {
	Provider string `json:"provider"`

	// Results Every candidate, best first.
	Results []RerankResult `json:"results"`
}

// RerankResult defines model for RerankResult.
type RerankResult struct {
	ID      string   `json:"id"`
	Reasons []string `json:"reasons,omitempty"`
	Score   float32  `json:"score"`
}

// RoleRequirements What the JD parser extracts. Maps onto roles.
type RoleRequirements struct {
	// Industries Industry context of the role, as taxonomy ids.
	Industries []string `json:"industries,omitempty"`

	// MustHaves Every hard requirement in the JD's own words.
	MustHaves []string `json:"must_haves,omitempty"`

	// NiceToHaves Preferred but not required, in the JD's own words.
	NiceToHaves []string `json:"nice_to_haves,omitempty"`

	// OtherIndustries Industries not in the taxonomy, verbatim.
	OtherIndustries []string `json:"other_industries,omitempty"`

	// OtherRequiredCertifications Required certifications not in the taxonomy, verbatim.
	OtherRequiredCertifications []string `json:"other_required_certifications,omitempty"`

	// OtherRequiredSoftware Required software not in the taxonomy, verbatim.
	OtherRequiredSoftware []string `json:"other_required_software,omitempty"`

	// RequiredCertifications Certifications the role requires, as taxonomy ids.
	RequiredCertifications []string `json:"required_certifications,omitempty"`

	// RequiredSoftware Software the role requires, as taxonomy ids.
	RequiredSoftware []string            `json:"required_software,omitempty"`
	StartsOn         *openapi_types.Date `json:"starts_on,omitempty"`

	// Timezone IANA name the role operates in.
	Timezone *string `json:"timezone,omitempty"`
	Title    *string `json:"title,omitempty"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Ctx   *map[string]interface{}    `json:"ctx,omitempty"`
	Input interface{}                `json:"input,omitempty"`
	Loc   []ValidationError_Loc_Item `json:"loc"`
	Msg   string                     `json:"msg"`
	Type  string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for .
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for .
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// EmbedJSONRequestBody defines body for Embed for application/json ContentType.
type EmbedJSONRequestBody = EmbedRequest

// ParseJdJSONRequestBody defines body for ParseJd for application/json ContentType.
type ParseJdJSONRequestBody = ParseJDRequest

// ParseResumeJSONRequestBody defines body for ParseResume for application/json ContentType.
type ParseResumeJSONRequestBody = ParseResumeRequest

// RerankJSONRequestBody defines body for Rerank for application/json ContentType.
type RerankJSONRequestBody = RerankRequest

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
